### ISSUE TITLE
"Cancel" and "Submit" buttons when selecting the details of an item in an article's history

### ISSUE THREAD

**Issue by a3nm** [CCSDForge/episciences#106]
Hi,

In the "History" section of an article's management page, when clicking on the entries for which details can be displayed, the form displaying the details has two buttons, "Cancel" and "Submit". Apparently, the two buttons have the same effect.

![2021-10-29-164214_1920x1080_scrot](https://user-images.githubusercontent.com/843551/139455407-ccf03363-0124-4bd9-95f5-0b7f00e52813.png)

This can be a bit confusing (e.g., it gives the impression that you can edit the submitted data). Do you agree it would make sense to replace them by a single "Close" button?

**Comment by rtournoy** [comment]
Yes, thanks, it has been fixed
