### ISSUE TITLE
Prevent submission of embargoed manuscript

### ISSUE THREAD

**Issue by laurentromary** [CCSDForge/episciences#108]
A paper (hal-03332534v1, jdmdh number 8468) was submitted to JDMDH whereas it was locked with an embargo. There are obviously several possible options to deal with this:

- allow editors and assigned reviewers to have access to the paper but this is a little contrary to the principles of post publication peer-review
- block this behaviour at submission time

**Comment by devletech** [comment]
This is indeed the case: Episciences blocks this behavior at the time of submission:  ![Capture d’écran du 2021-11-02 11-15-08](https://user-images.githubusercontent.com/20502173/139832497-2a2f399d-2284-4e9d-b3cc-59de4c205dae.png) The explanation is that the file was not under embargo at the time of submission.

**Comment by laurentromary** [comment]
Oh thanks. I'll check with the author.
