### ISSUE TITLE
Non-localized text in the details of comments to "Propose to accept the paper"

### ISSUE THREAD

**Issue by a3nm** [CCSDForge/episciences#110]
Hi,

When an editor proposes acceptance of a paper with the "Propose to accept the paper" feature, this creates a comment. When clicking the details of this comment in the article history box, there is a comment type field whose content says "suggestion d'acceptation du papier". The text is in French even though the rest of the interface is in English.

The non-localized text is here:
https://github.com/CCSDForge/episciences/blob/master/library/Episciences/CommentsManager.php#L40

Would it be possible to localize those? Thanks!

**Comment by rtournoy** [comment]
thanks, it has been fixed
