### ISSUE TITLE
Non-localized text when setting a reviewing deadline which is too large

### ISSUE THREAD

**Issue by a3nm** [CCSDForge/episciences#112]
Hello,

When an editor sends an invitation to a reviewer and sets a reviewing deadline which is too large, they receive a message which is not translated. For instance: " La date limite de relecture doit être comprise entre le 2021-11-07 et le 2021-12-31 ".

Would it be possible to localize this message?

Many thanks!

**Comment by rtournoy** [comment]
thanks, it has been fixed
