### ISSUE TITLE
Add release version on the interface (e.g., page footer?)

### ISSUE THREAD

**Issue by a3nm** [CCSDForge/episciences#116]
Hi,

It would be useful to know which version of the Episciences software a journal is currently using, to see if a given release has already been deployed or not. (The specific use case here is to see if 1.0.22 was deployed. :))

I'm thinking the simplest solution would just be to add the release number to the page footer, so that the information is visible.

Do you think this would be a good idea?

**Comment by rtournoy** [comment]
Hi, yes good idea! it will be for the next release, 1.0.22 is now deployed. thanks

**Comment by rtournoy** [comment]
Thanks, added and online with v1.0.23 (footer + dashboard)

**Comment by a3nm** [comment]
Awesome, thanks!
