### ISSUE TITLE
Les e-mails vides ne sont pas livrés au destinataire malgré notification d'envoi

### ISSUE THREAD

**Issue by CathScott** [CCSDForge/episciences#117]
TheoretiCS : Un e-mail vide n'est pas envoyé par exemple à l'éditeur ni reçu (alors qu'un message "_Your e-mail has been sent_" apparaît). -->Confirmer que quand la plateforme dit qu'un e-mail a été envoyé, alors il est vraiment envoyé.
Un e-mail qui est vide de contenu va se perdre dans les limbes d'Episciences (bien qu'une notification "Your e-mail has been sent" apparaît en effet sur la page). Par contre, un e-mail contenant ne serait-ce qu'un mot "bonjour" parviendra à son destinataire. https://support.ccsd.cnrs.fr/Ticket/Display.html?id=140896

-> Bloquer les messages avec corps du texte vide?
-> Pop up "contenu mail nécessaire?

**Comment by CathScott** [comment]
https://gitlab.ccsd.cnrs.fr/ccsd/episciences/-/issues/408

**Comment by rtournoy** [comment]
Thanks, fixed in production

**Comment by a3nm** [comment]
Merci beaucoup ! je ne peux pas tester facilement en prod sans risquer l'envoi d'un mail à un éditeur qui ne comprendrait pas, mais partons du principe que c'est réglé. :)

**Comment by devletech** [comment]
à tester en preprod : https://theoretics-preprod.episciences.org/

**Comment by a3nm** [comment]
Merci pour le pointeur ! Après test, il y a encore un problème, j'ai l'impression. Voici ce que j'ai fait :

- Envoi d'un message avec corps vide : le message est correctement envoyé, le corps de message est remplacé textuellement par "Empty message.", donc c'est parfait.
- Envoi d'un message avec sujet vide (que le corps soit vide ou pas) : le pop-up "Your e-mail has been sent." s'affiche mais à nouveau je ne reçois pas le message et le message n'apparaît pas dans l'historique de l'article.

Serait-il possible de corriger aussi pour que l'envoi d'un message où le sujet est vide réussisse, ou échoue d'une manière visible pour l'utilisateur, plutôt que de silencieusement perdre le contenu du message ?

Merci encore pour votre travail là-dessus !

**Comment by devletech** [comment]
Corrigé en prod + preprod

- Sujet vide + corps vide sans pièces jointes

        Votre message n'a pas pu être envoyé :
        Corps du message vide.

- Sujet vide + corps (texte || pièces jointes)  => mail OK

       Votre message a bien été envoyé.

**Comment by a3nm** [comment]
Bonjour, je viens de tester sur theoretics-preprod et l'envoi d'un message avec sujet et corps vide et pas de pièce jointe indique "Your e-mail has been sent.". Est-ce que c'est parce que les changements n'ont pas encore été déployés ?

**Comment by rtournoy** [comment]
bonjour, oui je pense que c'était parce que le code n'a pas été déployé - car je viens de mettre à jour et cela a fonctionné

**Comment by a3nm** [comment]
Merci pour cette précision, mais j'ai testé à nouveau sur theoretics-preprod et j'ai toujours le comportement en question: sur https://theoretics-preprod.episciences.org/administratepaper/view?id=809 envoyer un mail à " Antoine Amarilli (editor)", valider, le message "Your e-mail has been sent." s'affiche mais rien n'apparaît dans l'historique de l'article. Est-ce que vous parvenez à reproduire ? Merci beaucoup !

**Comment by rtournoy** [comment]
oui en effet, merci ! on vient de voir que le comportement est différent

**Comment by a3nm** [comment]
Ça marche, je vous laisse regarder ! désolé dans ce que j'avais écrit j'ai oublié de dire que je vidais le sujet et le corps du message avant d'envoyer.

Prévenez-moi quand c'est réglé pour vous et je testerai à nouveau. :)
