### ISSUE TITLE
Feature request: making revision deadlines editable by editors

### ISSUE THREAD

**Issue by smilius42** [CCSDForge/episciences#118]
Dear colleagues,

there should be a new feature implemented by which the deadlines for a (minor or major) revised version of a submission can be edited by the handling editor of a submission (and by admins, of course). 

At the moment the deadline is displayed in the 'Revision requests' box on the administration page of a submission but cannot be changed by any user. However, deadline extensions are frequently granted by editors, and in this case automatic reminder emails  should be stopped until the extended deadline. 

Best regards,
Stefan Milius

**Comment by devletech** [comment]
Idem #367: @ see https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#1041---2023-11-27
