### ISSUE TITLE
Refining automatic notifications when abandoning submission

### ISSUE THREAD

**Issue by smilius42** [CCSDForge/episciences#124]
Dear colleagues,
here is a request for refining an automatic notification feature of Episciences in connection with abandoning a publication.

Currently, when I hit 'Abandon publication process' for a submission, then the systems sends a notification to all reviewers (if any are assigned to the submission).

I would like to propose the following refinement of this functionality: the notification to reviewers should only be sent to those reviewers from whom a report is still pending.

For example, consider lmcs #4559 which I have just abandoned. Both referees have received an automatic notification even though there is currently no report expected from them. (In fact, the reason I was stopping this submission is that the revised version from the author is much overdue, and I do not really expect it to come any time soon.) In this case the referees should not be informed. However, there may be cases in which one of two reports is there and one is still expected. In such a case one referee should be informed - the one whose report is pending.

Best regards,
Stefan

p.s. Copied from https://support.ccsd.cnrs.fr/SelfService/Display.html?id=126819

**Comment by HeleneLowinger** [comment]
tests Ok pour moi (le relecteur qui a fini sa relecture ne reçoit rien, celui qui a commencé reçoit un message, comme celui qui n'a pas encore commencé)

**Comment by rtournoy** [comment]
completed, we forgot to close the issue
