### ISSUE TITLE
Clicking outside of the window to compose an email closes the window with no confirmation

### ISSUE THREAD

**Issue by a3nm** [CCSDForge/episciences#126]
Hi,

I have another UX annoyance to report following the launch: composing an email in the system (e.g., using the "Contact this contributor" feature) is done within a modal. Accidentally clicking outside the modal immediately closes it with no confirmation message, losing everything typed so far.

Would it be possible to change the Javascript so that clicking outside the modal doesn't close it, and/or putting a confirmation message if the message had already been edited?

Thanks!

**Comment by rtournoy** [comment]
Thanks for the report, the UI has been updated in production
