### ISSUE TITLE
TheoretiCS : un seul des 2 fichiers .txt (reviews) s'affiche dans le mail d'envoi de modifications mineures à l'auteur

### ISSUE THREAD

**Issue by CathScott** [CCSDForge/episciences#136]
Demande de Theoretics (03/01/2022) : [https://support.ccsd.cnrs.fr/Ticket/Display.html?id=143930]

-	Dans le cas où il y a par exemple 2 reviews (cf° #8788), le mail d’envoi à l’auteur de demande de modification mineure n’affiche pas la liste des différents reviews dans l’e-mail, seulement le 1er review ; de ce fait l’expéditeur peut penser que l’e-mail est incomplet. Cependant, le destinataire reçoit bien les 2 reviews.
![image](https://user-images.githubusercontent.com/91665367/147944620-f441fd2e-2413-4db9-be90-0e0709bdae9d.png)

-	J’ai fait le test dans epi-preprod (#1440) et il semble pourtant que mon draft de mail reprend bien les 2 reviews (je ne l’ai pas envoyé pour que vous puissiez le regarder) :
![image](https://user-images.githubusercontent.com/91665367/147944655-42711c5d-8e4b-4ca4-9464-48b25927e50d.png)
![image](https://user-images.githubusercontent.com/91665367/147944665-1f4c6120-782c-4cef-bb85-661b0439604d.png)

-	J’ai comparé le template de mail de TheoretiCS avec celui de notre base de preprod et c’est bien le même tag : **%%PAPER_RATINGS%%**

--> Voyez-vous d’où peut venir ce problème d’affichage ?

**Comment by devletech** [comment]
@rtournoy Le fichier manquant est destiné aux rédacteurs (paramétrage de la grille > **visibilité = rédacteur**)

**Comment by rtournoy** [comment]
Le fichier a été uploadé sur le mauvais critère, ce qui le rend confidentiel
