### ISSUE TITLE
Put newly created volumes at the top of the list

### ISSUE THREAD

**Issue by TobiasKappe** [CCSDForge/episciences#139]
When I create a new (regular) volume, it appears at the bottom of the list in `/volume/list`. This means that when the volume is closed, it will also appear at the very end of the publicly available list at `/browse/regularissues`.

At LMCS, we think it's reasonable to list the newest volumes first. This means that we must manually drag the volume to the top of the list every time we create one.

Would it be feasible to put newly created (regular) volumes at the top of the list?

**Comment by rtournoy** [comment]
Closed with [today's release](https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#104021---2023-11-14)
