### ISSUE TITLE
Visibility of LMCS pages is wrong on https://lmcs.episciences.org/website/menu

### ISSUE THREAD

**Issue by a3nm** [CCSDForge/episciences#141]
Hi,

On the page https://lmcs.episciences.org/website/menu the "Page visibility" field of all pages is initialized to "Public", even for the pages "Guideline for Editors" and "Test page" which are not currently public (and indeed, they shouldn't). For this reason, editing anything else in this form and saving it will overwrite the visibility of these pages to "Public".

I think there is a problem, and that the pre-filled values in the form for the "Page visibility" field is erroneously "public" instead of being correctly generated from the current setting.

Would it be possible to fix this?

(I couldn't reproduce the same problem on theoretics-preprod, so it may be specific to the LMCS instance.)

**Comment by rtournoy** [comment]
Thank you very much for the report, it is fixed in production. The menu ACL were stored in the user session and persisted in a file.
The file was used to apply the ACLs but not when loading the menu to be updated into the user interface by an administrator.

**Comment by a3nm** [comment]
Great, many thanks!
