### ISSUE TITLE
Harmonisation nombre de caractères login

### ISSUE THREAD

**Issue by cbarthonnat** [CCSDForge/episciences#159]
À la création d'un compte, il est demandé de choisir un **login** de **3 caractères minimum** (ex 1 : https://epi-preprod.episciences.org/user/create).
Or, quand on a oublié son mot de passe et que l'on souhaite le modifier, il est demandé de renseigner son login, "Entre 2 et 100 caractères" (ex 2 : https://epi-preprod.episciences.org/user/lostpassword).
Peut-on harmoniser pour mettre 3 caractères partout ? Donc modifier la page de modification de mot de passe (ex 2) ainsi : "Entre 2 et 100 caractères" -> "Au moins 3 caractères."

**Comment by rtournoy** [comment]
On ne peut pas harmoniser à cause d'un incompatibilité historique dans HAL :(
