### ISSUE TITLE
Updates to review deadline do not show up in "History" tab for article

### ISSUE THREAD

**Issue by a3nm** [CCSDForge/episciences#168]
Hello,

I have tried the "Edit the reviewing deadline" feature for the article https://theoretics-preprod.episciences.org/administratepaper/view?id=808

This has correctly sent an email (see https://theoretics-preprod.episciences.org/administratemail/view?id=53212) and updated the reviewing date.

However, there is no trace of this action in the "History" tab of https://theoretics-preprod.episciences.org/administratepaper/view?id=808

This can be a bit confusing, e.g., if an editor keeps postponing the deadline for a review without leaving a trace, it may be difficult to notice that there is a problem.

Do you think it would make sense that reviewing deadline extensions leave a trace in the "History" tab? Thanks!

**Comment by devletech** [comment]
https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#changed-1
