### ISSUE TITLE
Modification des volumes (y compris après publication des articles présents dans ces volumes) / Modification of volumes (including after publication of articles in these volumes)

### ISSUE THREAD

**Issue by CathScott** [CCSDForge/episciences#173]
Possibilité pour les éditeurs en chef de modifier les volumes y compris après publication des articles présents dans ces volumes
En cours de réflexion / faisabilité. Possibilité de donner la main aux éditeurs en chefs afin de modifier les volumes (et l'ordre des articles dans un volume) y compris quand l'article est publié. Analyse du risque / éventuelles répercussions. 
Laisser le choix à la revue dans les settings? Possible aussi si les DOIs n'ont pas de volumaison... /

Possibility for chief editors to modify volumes even after publication of articles in these volumes
Under review / feasibility. Possibility of giving the editors -in-chief the possibility to change volumes (and the order of articles within a volume) even when the article is published. Risk analysis / possible repercussions. Leave choice to the journal in settings? Possible also if DOIs have no volumetric...

**Comment by rtournoy** [comment]
At first it seems dangerous because the bibliographical informations, citations will be harvested/used in a lot of places. Not all will be updated. e.g. DOI, arXiv, HAL can be updated, but not the citations in papers.
