### ISSUE TITLE
add co-authors when submitting

### ISSUE THREAD

**Issue by Arolland-math** [CCSDForge/episciences#181]
Nouvelle fonctionnalité : il faudrait pouvoir ajouter les co-auteurs lors de la soumission afin qu'il puisse recevoir les notifications et suivre la vie de l'article de la soumission à l'acceptation.
on doit créer un compte aux co-auteurs (ou pas) et leur permettre de pouvoir refuser s'ils ne veulent pas (RGPD). Ils seront juste "lecteurs", on garde le contributeur comme référent. avoir un rôle supplémetnaire de consultation sur un article (obligation d'avoir un compte).

https://gitlab.ccsd.cnrs.fr/ccsd/episciences/-/issues/198

**Comment by emperrin** [comment]
Une autre demande pour cette fonctionnalité est portée par le ticket https://support.ccsd.cnrs.fr/Ticket/Display.html?id=171430

**Comment by rtournoy** [comment]
- L'auteur correspondant peut ajouter une autre personne qui a déjà un compte, cette personne aura un role 'co-auteur'
- le role co-auteur a le droit de voir les pages de gestion de l'article / pas d'action possible

**Comment by CathScott** [comment]
Je re-tag ce ticket en new car un coauteur de LMCS souhaite accéder à un papier déposé par un autre auteur (RT#187439)

**Comment by Arolland-math** [comment]
vu 26/06 : Julien fait un point sur ce qu'il a développé et revient vers nous.

**Comment by Arolland-math** [comment]
Depuis la page de l'article (une fois l'article soumis), les admin (pour le moment puis les auteurs pourront le faire) peuvent ajouter des co-auteurs : ils reçoivent alors les même mails que l'auteur en CC si case à cocher "envoyer une copie du message aux co-auteurs". Pour les mails auto, ils sont envoyés en CC.
Si le co-auteur clique sur le lien pour accéder à la page de l'article, il ne peut pas y accéder.
Les co-auteurs doivent avoir un compte CAS pour être rajouté

dispo en preprod
