### ISSUE TITLE
changement template par défaut :  Réponse à une demande de modifications : nouvelle version

### ISSUE THREAD

**Issue by Arolland-math** [CCSDForge/episciences#187]
Mettre l'information "L'auteur vient de vous proposer une nouvelle version de son article, consultable ici :" tout en haut du mail. (actuellement elle est tout en bas après les signatures).
+
rajouter un verbe à la première phrase actuelle du mail ( pas français)

**Comment by HeleneLowinger** [comment]
1ere partie faite, à retester

**Comment by Arolland-math** [comment]
à revoir pourquoi le tag %%REQUESTER_EXPRESSION%% n'est pas bien rempli

**Comment by Arolland-math** [comment]
ça donne ça : "Le 16 mars 2022, à l'auteur de l'article "#1490 - Pre-processed data of atlas in EUCP-WP2" la demande suivante :"
mettre plutôt: Le 16 mars 2022, la demande suivante a été faite à à l'auteur de l'article "#1490 - Pre-processed data of atlas in EUCP-WP2" :

**Comment by rtournoy** [comment]
Fixed in release https://github.com/CCSDForge/episciences/releases/tag/v1.0.33

**Comment by Arolland-math** [comment]
ce n'est pas fondamental mais la deuxième partie de la demande n'a pas été corrigée ...
on a toujours une phrase sans verbe (ci-dessous en gras) :
Bonjour Ariane Rolland,

L'auteur vient de vous proposer une nouvelle version de son article, consultable ici : https://rmath2.episciences.org/administratepaper/view/id/1577

**Le 18 octobre 2022, à l'auteur de l'article "#1577 - Étude asymptotique en temps d'un fluide visqueux axisymétrique sans swirl" la demande suivante :**

Dear Author1-IF,

The editorial board requests you to bring some major modifications to your article (#1530 - Time-Asymptotic Study of a Viscous Axisymmetric Fluid without Swirl), submitted on May 30, 2022.

Please give an answer to this request before the deadline: .

To answer this request, please go to: https://rmath2.episciences.org/paper/view/id/1530.




Sincerely yours,
--

**Comment by devletech** [comment]
Le tag **%%REQUESTER_EXPRESSION%%** n'est pas bien rempli car il n'est plus utilisé (https://rmath2.episciences.org/administratemail/tagslist#paper_new_version_submitted), je vais donc le remplacer dans le template par défaut par l’expression :  
[FR] vous aviez envoyé
[EN]  you've asked

**Comment by Arolland-math** [comment]
ok ! merci
