### ISSUE TITLE
Notification des  Editeurs en chef (et le cas échéant des Secrétaires éditoriaux) / Notification of the Chief Editor  (and possibly the Editorial Secretaries)

### ISSUE THREAD

**Issue by CathScott** [CCSDForge/episciences#188]
**Si l'option "Notification Settings" est décochée :**
_When an article is submitted, updated or refused, notify the:
- Chief Editors
- Administrators
- Editorial Secretaries__

**Alors l'Editeurs en chef  (et secrétaire éditorial) n'est pas informé des différentes modifications de statut du papier.**

Or, certains de ces changements de statut exigent une action de la part du Chief Editor, le process est alors interrompu.

> Exemples : 
- l'éditeur assigné clique sur "_I recommend to accept this paper_"
- l'auteur a déposé sa version finale et l'éditeur n'a plus la main pour intervenir (changement de statut grisé)

_Solution ?_
--> Soit une notification spéciale réservée aux cas qui nécessitent que l'éditeur en chef intervienne 
--> Soit le développement d'un module "_notifications_" qui permettrait de cocher le type de notifications que souhaite recevoir le Chief Editor (qui ne souhaite pas être envahi de notifications mais recevoir seulement les messages pour lesquels une action rapide ou essentielle est attendue sinon process interrompu et papier en stand by)...
--> ?

***

**If the "Notification Settings" option is unchecked:**
_When an article is submitted, updated or refused, notify the:
- Chief Editors
- Administrators
- Editorial Secretaries_

**Then the Chief Editors (and Editorial Secretaries) are not informed of the various status changes of the paper.**

However, some of these status changes require action by the Chief Editor, so the process is interrupted.

> Examples: 
- the assigned editor clicks on "_I recommend to accept this paper_"
- the author has submitted his final version and the editor no longer has the power to intervene (greyed out status change)

Solution?
--> Either a special notification reserved for cases that require the editor in chief to intervene 
--> Or the development of a "_notifications_" module that would allow to check the type of notifications that the Chief Editor wishes to receive (who does not wish to be invaded by notifications but to receive only the messages for which a fast or essential action is expected otherwise process interrupted and paper in stand by)...
--> ?

**Comment by CathScott** [comment]
Remplace le https://gitlab.ccsd.cnrs.fr/ccsd/episciences/-/issues/413

**Comment by CathScott** [comment]
Ok. Traité en attente de mise en prod prochainement.
A tester avant sur Epipreprod.

**Comment by CathScott** [comment]
Testé le 14/03/2022 sur Epipreprod #1486.
Ok : 
![image](https://user-images.githubusercontent.com/91665367/158206990-93991023-a5d5-4c2a-964d-40dd0e7bd90c.png)

**Comment by CathScott** [comment]
Test ok mais question @devletech 
Qui sont les destinataires en CC (D'où sont-ils extraits car à part Editor, personne assignée)?
![image](https://user-images.githubusercontent.com/91665367/158207705-5043ca39-75bf-4791-be1f-efa852c1fc14.png)
![image](https://user-images.githubusercontent.com/91665367/158207932-4775fd84-277d-4bdc-b2ef-38b0c5ff8bb3.png)

**Comment by rtournoy** [comment]
Fixed in release https://github.com/CCSDForge/episciences/releases/tag/v1.0.33
