### ISSUE TITLE
Bouton "changer le statut de l'article"

### ISSUE THREAD

**Issue by benoit-claudon** [CCSDForge/episciences#190]
Les éditeurs (EpiGA) n'ont que peu d'option lorsqu'ils cliquent sur le bouton "changer le statut de l'article". En tant qu'admin, j'en vois 5 (refuser, accepter, modifications mineures, modifications majeures, demander l'avis du comité) mais les éditeurs n'en ont que 3 (accepter, mineures et majeures) ; le fait de refuser un article s'affiche mais est grisé (donc non utilisable) si on est sur une version qui n'est pas la version 1 de l'article.
Il faut que les éditeurs puissent de nouveau demander l'avis des autres membres du comité via le système.
Merci d'avance
Benoît

**Comment by rtournoy** [comment]
TODO:
If Editors can refuse articles:
Allow them to refuse articles > version 1

**Comment by Arolland-math** [comment]
Voici les exemples demandés pour @devletech 
 - en tant que éditeurs,  je ne vois plus l'option "demander l'avis des autres rédacteurs", à aucune étape du workflow
ex : rmath2, article 1505, 1507
- en tant que éditeur, impossible de refuser l'article round 2 (1507)

**Comment by rtournoy** [comment]
La fonctionnalité 1 est disponible en ligne dès maintenant cf https://github.com/CCSDForge/episciences/issues/201

**Comment by devletech** [comment]
Corrigé par la version [1.0.32 - 2022-08-31](https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#changed-8)
