### ISSUE TITLE
"Name" => "Last Name" when creating a new reviewer

### ISSUE THREAD

**Issue by a3nm** [CCSDForge/episciences#196]
Hi,

On https://theoretics.episciences.org/administratepaper/invitereviewer the form to "Invite a new user" has first a field "Name" then a field "First Name"

![2022-03-11-112812_3600x1200_scrot](https://user-images.githubusercontent.com/843551/157849974-5a041b85-7099-42f0-8398-83bfbe20525d.png)

To avoid confusion: would it be possible to change the "Name" field to say "Last Name"?

Thanks!

**Comment by clason** [comment]
Might be a good chance to move to non-Western-centric terminology ("Family name"/"Given name")?

(Although some people -- for example in India -- only have a single name, where the current form (only "Name" mandatory) makes more sense...)

**Comment by a3nm** [comment]
Yes, the other option is to just have one "Name" field, to fill the reviewer's display name. Unless there is a need, e.g., to sort reviewers by last name in some list, I think this may be a better option.

**Comment by clason** [comment]
>  to sort reviewers by last name in some list, 

That is exactly what this is for, yes. The reviewer list has separate fields for first and last name that can be sorted independently (currently sorted by first name by default, which would be much more useful to be changed to last name sorting, but that's a different issue).

**Comment by rtournoy** [comment]
Thank you to both of you for the input:
- reviewers are now sorted by 'Name'
- Name has replaced first name + last name when inviting reviewers
- When users create an account they can add more information and use a 'screen name' (not new)
- We try to use the screen name if it is available

I find this document interesting:
https://www.w3.org/International/questions/qa-personal-names

**Comment by a3nm** [comment]
Hi, thanks for the fix. However, when the invited reviewer creates their account, apparently the fields "First name" and "Last name" are pre-filled in a strange way: "First name" is filled with the entire "Name" that was provided when inviting the reviewer, and "Last name" is empty. See attached screenshot, where the reviewer was invited by putting "Firstname Lastname" as the "Name".

![2022-09-06-173145_3600x1200_scrot](https://user-images.githubusercontent.com/843551/188676379-bd9d1fad-a891-40bd-b1ee-f857b84c79ad.png)

I think it would be more consistent to leave the two fields empty (so the reviewer fills them in), and only use the provided name as display name.

This is not too important, but just a bit confusing.
