### ISSUE TITLE
Review not easy to read because skip to the lines are missing / rapport de relecture illisible, sauts à la ligne disparus

### ISSUE THREAD

**Issue by HeleneLowinger** [CCSDForge/episciences#203]
rapporté par un relecteur de FI " I just sent the review of fi #8442. However, after saving and sending the review, all newlines were removed from my review, making it very hard to read. Would it be possible for you to fix  this?

**Comment by rtournoy** [comment]
Thanks, it has been fixed by release [V1.27.1](https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md)

**Comment by rtournoy** [comment]
the <br> element was stripped from the copy/pasted HTML

**Comment by a3nm** [comment]
Hi, is this also a fix of the seemingly related #132 ?

**Comment by rtournoy** [comment]
not really :( 
Because the problem comes from the JS Tinymce WYSIWYG tool that is no longer loaded at some point. We know why and will fix it but actually it's another problem
