### ISSUE TITLE
Editing the translation of Chief Editors // Modifier la traduction de Rédacteur en chef

### ISSUE THREAD

**Issue by HeleneLowinger** [CCSDForge/episciences#207]
(https://gitlab.ccsd.cnrs.fr/ccsd/episciences/-/issues/338)
Website: Editing the translation of Chief Editors
This request is related to ticket #118784 :
Change the translation of the heading "Chief Editors" to Editors in Chief (if plural) and Editor in Chief (if there is only one) See current posting: https://ojmnr-preprod.episciences.org/review/staff

(ask from MNA)

-------------------
Site web : Modifier la traduction de Chief Editors
Cette demande est en lien avec le ticket #118784 : 
Modifier la traduction de l'intitulé "Chief Editors" par Editors in Chief (si pluriel) et Editor in Chief (s'il n'y en a qu'un) Cf. affichage actuel : https://ojmnr-preprod.episciences.org/review/staff

**Comment by rtournoy** [comment]
Fixed in release https://github.com/CCSDForge/episciences/releases/tag/v1.0.33
