### ISSUE TITLE
Statistics // Statistiques

### ISSUE THREAD

**Issue by HeleneLowinger** [CCSDForge/episciences#208]
(https://gitlab.ccsd.cnrs.fr/ccsd/episciences/-/issues/19)
Etape 1.2
Pour AMS :
il faut les medians (ce qui fait statistiquement plus de sens).
"Moyenne" est différent de "médian" et il faut le médian pour AMS. Avoir les 2 données.
en particulier le median entre acceptation et publication

 Pouvoir afficher un tableau de tout ce qui a été fait dans la revue sur l'année et en bas la statistique.
en particulier le median entre acceptation et publication

Exemples : 
 Number of articles posted in 2017: ____
 Median time from ORIGINAL SUBMISSION to FINAL ACCEPTANCE for articles posted in 2017 (in days):
 Median time from FINAL ACCEPTANCE to POSTING for articles in 2017 (in days): ____

A faire plus tard :
Répartition par epi-comité (par thématique) (nécessite des modifications pour associer les revues à un épi-comité dans la base
Pour les rôles Rédacteur (dont rédacteur encapsulé) et Relecteur
Nombre de relances automatiques depuis l'outil : par année / par rôles / par compte (personne nominative)

Relances manuelles : impossible pour l'instant, pas de typage sûr des relances mails pour faire des stats
Relance automatique : impossible pour l'instant, pas de typage sûr des relances mails pour faire des stats

Pour un utilisateur /par UID (afficher uniquement sur le profil de l'utilisateur lui-même) :

 Nombre de rapporteurs invités.
 Nombre de rapporteurs ayant accepté de rapporter
 Nombre de rapporteurs ayant accepté et effectué réellement le travail

Pour un utilisateur / par UID :
 Le nombre d'articles attribués à un rapporteur
 Le nombre de fois que le rapporteur a refusé de rapporter

 En cas d'acceptation, et d'évaluation effectuée, le délai moyen de réponse

 Le nombre de fois ou le rapporteur a accepté le travail, mais ou il ne l a pas effectué ....

 nombre de relecteur / année

Etape 2 : Affichage dans l'application
Choisir composant JS
***Type d'affichage :
 texte et nombre
 Graphiques et diagrammes

Etape 3
***Exports :
txt
csv
pdf
graphique

***Consultations de pages :
 Piwik/Matomo - CCSD

***Consultations de papiers/notices
 Nombre de téléchargement PDF
 Nombre de consultation de notices de l'article
 Provenance / Pays des téléchargements

**Comment by HeleneLowinger** [comment]
(spécification de Theoretcis, sera demandé aussi par les autres revues:  )
" Les statistiques dont on a besoin sont celles demandées par KOALA :
>       • Number of submissions
>       • Number of reviews requested
>       • Number of reviews received
>       • Number of accepted submissions
>       • Average time between submission and publication."

**Comment by HeleneLowinger** [comment]
et la page des statistiques doit être accessible quand on est un simple utilisateur
(des futurs auteurs nous demandent souvent le taux d'acceptation, ou le délai avant acceptation, etc)

**Comment by emperrin** [comment]
Pour information, la page Statistique de la revue TheoretiCS : https://theoretics.episciences.org/page/statistics

**Comment by HeleneLowinger** [comment]
Demande complémentaire de Laurent Romary : 
" évolution des consultations des articles (via le site, via l’archive ouverte) et les répartitions géographique des auteurs"

**Comment by a3nm** [comment]
Dear Episciences,

I would be interested to know if there has been progress about the possibility for journals to automatically compute and make available some statistics about the journal.

Indeed, making journal statistics available seems to be a good practice. A survey by the Free Journals Network asked us at TheoretiCS whether we annually publish statistics. Further, Plan S [requires the yearly publication of statistics](https://www.coalition-s.org/technical-guidance_and_requirements/): the number of submissions, the number of reviews requested, the number of reviews received, the approval rate, and the average time between submission and publication.

Would it be possible for the Episciences platform to allow journals to create a public webpage containing the statistics in question? (If possible updated more regularly than annually, though it would be useful to have the statistics bucketed by year to see the evolution.)

At TheoretiCS it would be especially interesting to have a statistic about the "delay to first get back to the authors" (i.e., time between article submission and the article being rejected, accepted, or sent for minor or major revision). We also believe that the "the average time between submission and publication" should not include the time that articles spend waiting for the authors (i.e., pending minor revision or pending major revision).

Do you feel that public statistics of this form would be possible? Many thanks!

**Comment by rtournoy** [comment]
Hello, yes. We are in the process of redesigning the public web pages of the journals and are including some KPI for the journals, for instance those proposed by Plan S. There are several Issues created with theses questions so I will create a meta-issue or a project to handle the requests and gather feedback in one place

**Comment by rtournoy** [comment]
See also #339

**Comment by rtournoy** [comment]
moved from #339 :

Add statistics in the Statistics module for :   
- Number of revisions requested
- Number of revisions received

**Target for 2024:** 
Key statistics published annually:
   - Number of submissions
   - Number of reviews requested
   - Number of reviews received
   - Number of accepted submissions
   - Average time between submission and publication.

[cf° RT Ticket URL: https://support.ccsd.cnrs.fr/Ticket/Display.html?id=170781]

**Comment by Arolland-math** [comment]
meta-ticket #452
