### ISSUE TITLE
Capitalization of names / emploi des majuscules dans les noms propres / Middle Name

### ISSUE THREAD

**Issue by emperrin** [CCSDForge/episciences#212]
[https://support.ccsd.cnrs.fr/Ticket/Display.html?id=148137]

On constate une différence entre l’écriture des noms et prénoms dans le profil de l’utilisateur et les noms et prénoms de l’utilisateur tels qu’ils apparaissent dans le champ du destinataire du mail, où le deuxième prénom et le deuxième nom n’ont pas de majuscule.
On remarque aussi que le nom s’affiche correctement dans les templates de mail avec le tag %%Recipient_screen_name%% et pas avec le tag %%Reviewer_full_name%%.

There is a difference between the capitalization of the first and last names in the user's profile and the first and last names of the user in the email recipient field, in which the second first and last names are not capitalized)
We also notice that the capitalization of the user name is correct in the mail templates with the %%Recipient_screen_name%% tag and not with the %%Reviewer_full_name%% tag.

**Comment by HeleneLowinger** [comment]
complément de Jens du 22 avril 
" Dans le corps de mail, p.ex là je suis en train d'un faire un et le destinataire apparait comme 
Mbe koua christophe Ndjatchi"

**Comment by rtournoy** [comment]
Test ok by @emperrin

**Comment by rtournoy** [comment]
Fixed in release https://github.com/CCSDForge/episciences/releases/tag/v1.0.33

**Comment by emperrin** [comment]
J'ai informé l'auteur du ticket qu'une meilleure gestion de la capitalisation des noms propres a été mise en production dans la version 1.0.33 d'Episciences. Les notes de mise à jour complètes sont disponibles en ligne :
https://www.ccsd.cnrs.fr/2022/09/notes-de-mise-a-jour-episciences-pour-la-version-1-0-33/
Il répond qu'il semble que le problème du middle name manquant persiste. Il a testé sur l'article qui était à l'origine de du  ticket,

Quand il ouvre le popup pour écrire un mail à l'autrice correspondante
ça me mets "First Name Family Name" où bien la base des utilisateurs me dit First Name Middle Name Family Name-Family Name (la personne porte un nom de famille composé)

On constate donc que pour le membre 1002704 :
le screen name est : First Name Middle Name Family Name-Family Name
l'user name : First Name Family Name
et enfin pour "my account" : First Name Family Name-Family Name.

Et c'est apparemment le nom correspondant dans "my account"  qui apparaît dans l'adresse mail et avec toujours un problème de capitale au second nom propre.
Comment est formé le nom affiché dans "my account" ?
Ne serait-il pas possible d'afficher devant l'adresse e-mail le "screen name" ?

**Comment by rtournoy** [comment]
Fixed by https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#10382---2022-11-24
