### ISSUE TITLE
[JTCAM] [arxiv] Supplementary material DOI cannot be indicated

### ISSUE THREAD

**Issue by mlegr** [CCSDForge/episciences#213]
Supplementary material DOI can be indicated on HAL. They are then automatically retrieved by the Episciences platform (see [1] for instance). However, it does not seem possible to achieve the same with the arxiv platform. Could it be instead possible to indicate this type of additional information directly on the JTCAM platform?

[1] https://doi.org/10.46298/jtcam.6450

**Comment by rtournoy** [comment]
Fixed with release [v1.0.41](https://github.com/CCSDForge/episciences/releases/tag/v1.0.41)
