### ISSUE TITLE
Each editor can save his own templates

### ISSUE THREAD

**Issue by HeleneLowinger** [CCSDForge/episciences#219]
[https://gitlab.ccsd.cnrs.fr/ccsd/episciences/-/issues/309]
I'm wondering whether it'd be possible for an editor to save her/his own templates for the usual letters sent (e.g. refereeing invitations, acceptance of article, rejection and so on). It's not a major thing as one can always copy/paste from a local text file, but that could be helpful.
Best regards, Jean-Sébastien Sereni [DMTCS]

**Comment by Arolland-math** [comment]
pas possible de personnaliser les templates pour chaque utilisateurs
