### ISSUE TITLE
DOI non visibles dans HAL

### ISSUE THREAD

**Issue by HeleneLowinger** [CCSDForge/episciences#224]
[https://gitlab.ccsd.cnrs.fr/ccsd/episciences/-/issues/357]

Les DOI ne semblent pas visibles dans HAL
Ex : https://arima.episciences.org/5802 VS https://hal.archives-ouvertes.fr/hal-01898913v3
Contrairement à arXiv :
https://dmtcs.episciences.org/5340 => https://arxiv.org/abs/1810.13300v3

**Comment by rtournoy** [comment]
merci c'est corrigé ;)
