### ISSUE TITLE
feature request: revoking automatic reassignment of reviewers

### ISSUE THREAD

**Issue by smilius42** [CCSDForge/episciences#232]
It would be nice if editors could revoke the 'automatic reinvitation of reviewers' option after they have sent out the notification to the authors and before the revised version has been submitted.

**Comment by CathScott** [comment]
After examination of this ticket: the requested development is too complex in relation to the expected benefit.  We suggest that you get around this by unchecking the box in the settings and then selecting the desired reviewers on a case-by-case basis in future rounds.
