### ISSUE TITLE
Editor comments div is too small

### ISSUE THREAD

**Issue by a3nm** [CCSDForge/episciences#237]
Hi,

At TheoretiCS we use the "Editors comments" feature heavily to discuss papers. It is a problem for this that the div showing these comments is very small (only 200px of height), making it difficult to read long discussions.

As a first fix, would it be possible to change this max-height value to something more reasonable, like 800px? It is here:

https://github.com/CCSDForge/episciences/blob/a8d6dac1a8f371ba2f823feaef416f77e8c021e5/application/modules/journal/views/scripts/partials/paper_editor_comments.phtml#L7

Ideally, I guess the best fix would be to have a link to open the discussion about a paper in a separate window.

Thanks a lot!

**Comment by rtournoy** [comment]
Hi,
ok updated to 800px,
thanks

**Comment by rtournoy** [comment]
Fixed in release https://github.com/CCSDForge/episciences/releases/tag/v1.0.33
