### ISSUE TITLE
Behaviour of setting "Display ratings reports on the article page"

### ISSUE THREAD

**Issue by smilius42** [CCSDForge/episciences#240]
The behaviour of the Rating setting "Display rating reports on the article page" should be changed.
Reviews should become visible to authors when a) all reviews have been received and b) the editor has sent the notification (accept/reject/minor revision/major revision) to authors.

Btw, the name of the setting should be changed to "Display reviews on the article page".
In general 'rating' should be replaced by 'review' or 'referee report' in everywhere.

**Comment by HeleneLowinger** [comment]
1er partie faite / 1st part ok, done.
2e (changer 'rating') ok, sera fait progressivement, mais il faut changer les captures d'écran de la doc. /  God idea, it will be made progressively (and need a change in the documentation)
