### ISSUE TITLE
Copyediting: "author's final version submitted" email contains wrong attachment

### ISSUE THREAD

**Issue by clason** [CCSDForge/episciences#243]
At JNSAO, we ask the authors to carry out the copyediting. When a final formatted version is submitted, the managing editors are notified via email (e.g., with subject "jnsao #9193 - author's final version submitted"). However, the PDF that is attached to this email is _not_ the final version but the first submission.

(On the administration page for this paper in the "Copy editing" tab, where the submission letter from the author is shown, the attachment is correct. So this is not a blocking bug if you know where to look.)

I believe this is a new bug that only started occurring recently (but consistently).

**Comment by Arolland-math** [comment]
Hello Christian, 
Do you still see this bug at JNSAO? 
For me, it works normally...
Thanks for your answer.

**Comment by clason** [comment]
I haven't had a chance to test this recently, unfortunately...

But I'll keep an eye out!

**Comment by Arolland-math** [comment]
ticket closed, reopen if necessary
