### ISSUE TITLE
Incohérence des messages reçus par les relecteurs / Inconsistency of messages received by reviewers

### ISSUE THREAD

**Issue by emperrin** [CCSDForge/episciences#244]
**Please do not disclose any personal information (e.g. name of an author, reviewer, email addresses, etc.).**

Please use the support address if you need to mention personal data

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by emperrin** [comment]
Arima article #8660   

Alors que le second relecteur, dont la relecture est en cours, a reçu le 20 mars le message "reviewing is no longer needed" quand des révisions majeures ont été demandées, il a reçu le 17 mai un message de rappel "Reviewing deadline is over !" quand le statut de l'article a été mis à jour.

While the second reviewer, whose reviewing is pending, received a message "reviewing is no longer needed" on 20 March when major revisions were requested, he received a reminder message "Reviewing deadline is over! on 17 may when the status of the article has been updated.

**Comment by devletech** [comment]
@emperrin 

Au 17 mai 2022 – 00:07, la date limite de livraison de la relecture est dépassée de 77 jours, d’où l’envoi de la relance. 

Le refus, acception ou **demande de modifs ** . `(20 mars 2022 14:00:35 Demande de modifications majeures)`  rend  obsolète toutes les relectures en cours (non achevées) d’où le message informant le relecteur de la non nécessité de poursuive sa relecture.
