### ISSUE TITLE
[Bug Report] HTML links in outgoing emails are made relative

### ISSUE THREAD

**Issue by a3nm** [CCSDForge/episciences#247]
When sending an email using the mailing module, e.g., for TheoretiCS, at https://theoretics.episciences.org/administratemail/send, if adding a link to a page of the journal, the link does not work in the email which is sent.

## Steps to reproduce

Go to https://theoretics.episciences.org/administratemail/send

Add to the email a link to https://theoretics.episciences.org/page/advisory-board, see attached:

![2022-05-30-140258_3600x1200_scrot](https://user-images.githubusercontent.com/843551/170989856-b03a0794-1f7b-42cd-9918-ae6bc94f68db.png)

Send the email.

In the received email, the link does not work. The HTML MIME part of the email contains:

```
<p><a href="page/advisory-board">advisory board</a></p>
```

and the text part of the email contains:

```
advisory board [/page/advisory-board]
```

## Explanation

It appears that the platform transforms the absolute URL into a relative URL. This can be seen by clicking again on the button used to make a link before sending the message. See attached:

![2022-05-30-140258_3600x1200_scrot](https://user-images.githubusercontent.com/843551/170989885-3f785dfd-2bb9-4285-b8f1-8200ead758e0.png)

So I think the fix is to ensure that, at least in the mailing module, absolute URLs to the website are not made relative, because the relative URLs do not work in the sent email.

**Comment by rtournoy** [comment]
Many thanks for this clear bug report, @devletech has fixed the issue

**Comment by a3nm** [comment]
Indeed, this seems fixed now, thanks!
