### ISSUE TITLE
[Bug Report] Langues d'affichage des titres au niveau des volumes (Slovo)

### ISSUE THREAD

**Issue by cbarthonnat** [CCSDForge/episciences#254]
Au niveau de la gestion du volume : https://slovo.episciences.org/volume/edit?id=652, les titres apparaissent en cyrillique quand plusieurs langues ont été introduites dans les métadonnées côté HAL, voir pas de titre du tout (#9677, #9678, #9679).

**Comment by devletech** [comment]
https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#fixed-1
