### ISSUE TITLE
[JTCAM][Feature request] Refused article: editor's message to the authors automatically sent to the reviewers

### ISSUE THREAD

**Issue by mlegr** [CCSDForge/episciences#278]
As far as we know at JTCAM, in case an article has been refused, the message sent to the authors explaining the final decision made by the editor in charge is not forwarded automatically to the reviewers. Could this be implemented or at least an option for the editor to easily CC the reviewers without having to go back in the interface to search for reviewers' email addresses, which is error-prone.

**Comment by Arolland-math** [comment]
need test ? (c'est pour nos tris de tickets ;-))

**Comment by devletech** [comment]
Optional: https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#changed-7
