### ISSUE TITLE
[Feature request] [JTCAM] Article_ID, Document_ID, Permanent_ID

### ISSUE THREAD

**Issue by mlegr** [CCSDForge/episciences#288]
When emails are sent from the JTCAM plateform, the tag %Article_ID% is available. However, it is not clear whether it refers to the Document_ID or the Permanent_ID assigned to every paper. This should be clarified. Also, in most messages sent by the interface (for instance, when a new paper is submitted), the Document_ID (which depends on the version of the document) is indicated in the title. The Permanent_ID should be indicated as well for retrieval purposes.

**Comment by vacary** [comment]
It seems that there is also %%PAPER_ID%% in the tag list, but is there a difference?

**Comment by a3nm** [comment]
This seems related to #160

**Comment by devletech** [comment]
https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#10391---2022-01-19

**Comment by vacary** [comment]
Perfect. Thank you.
