### ISSUE TITLE
lmcs #9788 - bug with review invitation date

### ISSUE THREAD

**Issue by smilius42** [CCSDForge/episciences#293]
I have just cancelled a reviewer invitation to Douglas Bridges for submission lmcs #9788. 
When I look at the cancelled invitation in the 'Reviewers' box it states 'Invitation sent on: December 9, 2022' (today)
But the invitation was sent on December 1 as one can see from the 'History' box. 

It seems that the system has overwritten the invitation date with the date of the cancellation.

**Comment by rtournoy** [comment]
Thank you for noticing and reporting this bug, we have just pushed a fix online
