### ISSUE TITLE
Small problems with the conflict of interest dialog

### ISSUE THREAD

**Issue by a3nm** [CCSDForge/episciences#294]
I see two small problems with the conflict of interest dialog (see screenshot):

![2022-12-14-124913_3600x1200_scrot](https://user-images.githubusercontent.com/843551/207588061-76f4b35c-8e35-4e21-802b-fe02b374f137.png)

- "continue and access the submission" is missing a capital
- "Ne pas accéder à la soumission" etc should be in English, not French

Thanks!

**Comment by rtournoy** [comment]
Thanks @a3nm for the report and @devletech for the fix, it's online
