### ISSUE TITLE
[Feature request] Permanent id: a tag?

### ISSUE THREAD

**Issue by benoit-claudon** [CCSDForge/episciences#295]
Dear Episciences,
it would be desirable to have access to a new tag ARTICLE_PERM_ID (or something like that) in the templates concerning reviewing invitation. Indeed, as far as EpiGA is concerned, sometimes the referees (and some editors) are confused when the ID of the article changes. I know that it is important for technical reason to to attribute to each version a new id but it's better for the scientific assessment to have a consistent way to refer to the paper. That's why it's better to use the permament ID when communcating with the referees and the board.
Best,
Benoît

**Comment by benoit-claudon** [comment]
sorry... I just realized that this request was recently submitted by JTCAM...

**Comment by Arolland-math** [comment]
https://github.com/CCSDForge/episciences/issues/288

**Comment by rtournoy** [comment]
Closed because it will be fixed by #288 , thanks for the explanation
