### ISSUE TITLE
"answer this request" : too many possibilities // répondre à cette demande : possibilités de réponse inappropriées

### ISSUE THREAD

**Issue by HeleneLowinger** [CCSDForge/episciences#296]
When an editor has accepted a temporary version (or accept the refusal from the author to send a revised version), The status is "Accepted temporary version, waiting for author's final version" 
At this step, the system should propose only to the author to send a new version,  but the system still propose to the author to contact without modification, or send a new temporary version.

![Capture d’écran 2022-12-16 à 18 03 04](https://user-images.githubusercontent.com/91547400/208151078-eeb18042-212b-4398-ad0e-b5959c1f2c31.png)

(see https://epi-preprod.episciences.org/paper/view?id=1603 as the author)
-----------------------
français : 
Quand un éditeur accepte une version temporaire (même si la réponse d l'auteur a été "répondre sans modifications"), di moment que l'éditeur accepte cette version et décide de donner suite en demandant à l'auteur de déposer la version finale sur l'archive, le système ne doit plus proposer à l'auteur autre chose que "proposer une nouvelle version" (qui devrait certainement d'ailleurs s'appeler plutôt en français "déposer une nouvelle version"). Actuellement, le système propose à nouveau de répondre sans document, ou sans modification ou avec une version temporaire, ce qui n'est pas approprié.

Merci,
Hélène

**Comment by rtournoy** [comment]
- leave Contact
- leave 'upload new version'
