### ISSUE TITLE
[Feature request] [JTCAM] Optional file attachment button in "Contact without sending a new version"

### ISSUE THREAD

**Issue by mlegr** [CCSDForge/episciences#313]
At JTCAM, when minor versions only are requested, the authors are asked to submit the new version of their manuscript directly to the JTCAM platform and not to the Open Archive initially used (HAL, arxiv,...). In order to do so, they can use the "Revision requests" tab and then the option "Contact without sending a new version". However, there is currently no possibility to add an attachment. This is annoying because this is how the authors could submit their new version (as a pdf file) for a final check before final approval. Currently, authors can only add a link to a (personal or professional) repository where the pdf could be downloaded. This is not optimal because not all authors have access to such a service.

An attendant feature request is that the message with the attachment should be easily shared with the reviewers. In the current version of the platform, this message is probably only visible to the editor in charge of the paper.

![Attach](https://user-images.githubusercontent.com/92648586/216776353-b97188bf-7ef0-43e0-82de-322d3663df21.png)

**Comment by devletech** [comment]
I invite you to explore this option: 
![Capture d'écran du 2023-02-06 09 10 45@2x](https://user-images.githubusercontent.com/20502173/216932975-71d7398e-469c-4b0c-ada6-c7fd8ac4b64f.png)

**Comment by mlegr** [comment]
Yes, it looks interesting. However, I'm not sure what are the available options for the editors after this temporary version has been submitted? They can accept it and proceed with additional options such "Accept paper"?

**Comment by mlegr** [comment]
We've tested this "temporary version" option and this looks promising but there is a missing step. Once this temporary option has been accepted by the editor in charge, the next available step is "Accepted temporary version, waiting for author's final version". However, at JTCAM, final edits are made by the journal and not the authors. The authors should then be allowed to "upload the source files of their paper".

**Comment by mlegr** [comment]
Ok, we now have a better understanding of the "temporary version" feature [1] and it does not behave in the way we would like it to behave. Essentially, in its current form, only when minor changes are needed, it does not allow the editor to "skip" a new deposit on the selected open archive, while this is what we would like to achieve. Ways to "fix" the problem are the following:

1. With the current "temporary version" [1] feature enabled, when the current status is "Reviewed", add an additional option saying "Paper accepted. (Final edits made by the journal)" [or something similar, in line with the options for papers for which temporary versions are not requested).

![JTCAM](https://github.com/CCSDForge/episciences/assets/92648586/1280e84e-4bc4-46ab-9a3b-d1a8e1ef0ce6)

2. With the current "temporary version" [1] feature disabled, during the review procedure, a new option saying "Ask for a minor revision (temporary version)" should be implemented. The current option "Ask for a minor revision" requests a new deposit on the selected open archive while the new option "Ask for a minor revision (temporary version)" would not. The new version with the minor changes would be stored as an attachment and, upon approval, the editor would be able to choose the "Paper accepted" option.




[1] "Contributors can answer revision requests with a temporary version"

**Comment by rtournoy** [comment]
Fixed with release [v1.0.41](https://github.com/CCSDForge/episciences/releases/tag/v1.0.41)
