### ISSUE TITLE
[Feature request] Traduction EN "Détails de la réponse"

### ISSUE THREAD

**Issue by cbarthonnat** [CCSDForge/episciences#315]
Il manque la traduction en anglais "Détails de la réponse" dans la page "Paper reviewing invitation". Je suggère d'indiquer "Details of the answer".

ex : https://epi-preprod.episciences.org/reviewer/invitation/id/1602

![review-2](https://user-images.githubusercontent.com/91331602/217763313-c5197aac-2998-4823-ab47-5d16ef860fbc.png)

**Comment by rtournoy** [comment]
fixed in v1.0.39.5
