### ISSUE TITLE
[Feature request]  Refuser de relire un article sans créer de compte / Declining a review without creating an account 

### ISSUE THREAD

**Issue by emperrin** [CCSDForge/episciences#316]
ticket RT https://support.ccsd.cnrs.fr/Ticket/Display.html?id=178989

Des utilisateurs se plaignent de devoir se créer un compte juste pour refuser d'évaluer un article. 
Il a déjà été discuté de la possibilité de créer des liens uniques, pour qu'à minima un extérieur puisse refuser d'évaluer un article,  ou mieux, de pouvoir aussi accepter, sans créer un compte, et d'avoir un lien unique
pour envoyer son rapport. Avez-vous prévu d'implémenter cette option ?

Some users are complaining about having to create an account just to decline to review an article. The possibility of creating unique links, so that at least an outsider can decline to review an article, or better yet, be able to accept and provide a report without creating an account, has already been discussed. Have you planned to implement this option?

Voir aussi #253

**Comment by rtournoy** [comment]
fixed in production with v1.0.39.5
