### ISSUE TITLE
[Bug Report] Reviewing invitation

### ISSUE THREAD

**Issue by benoit-claudon** [CCSDForge/episciences#318]
I think a bug occurs when inviting reviewers. Some editors reported me that reviewers were in trouble: they created an account when accepting an invitation and after that, they weren't able to locate the article in their account.
Today, I tried to accept an invitation on behalf of a reviewer: I copy/paste the invitation link in Firefox and instead of getting the traditional page with the title/abstract of the article and the two buttons green/red to accept/decline, I got the page "Creating an account"... I think it is not the expected way. And now I understand why the initial invitation was not linked with the created account.
Benoît

**Comment by benoit-claudon** [comment]
I think it is related with the content of the previous issue listed:
https://github.com/CCSDForge/episciences/issues/316
Indeed, up to now it was not needed to create an account when declining an invitation!! It was enough to click on the red button...

**Comment by Arolland-math** [comment]
Si le relecteur n'est pas connu de la plateforme, et qu'il accepte de relire l'article la plateforme crée un compte temporaire, tant que la personne ne s'est pas crée un compte (n'a pas validé son compte temporaire), elle ne peut pas accéder à son dashboard avec la relecture. 
Pour le ticket 316, il s'agit des relecteurs qui ne veulent pas relire l'article, désormais ils n'ont plus besoin de se créer un compte.
Je laisse Djamel compléter éventuellement cette réponse.

**Comment by benoit-claudon** [comment]
le bug s'est reproduit. Un éditeur a invité une collègue et quand elle a voulu accepté l'invitation, elle a été renvoyée vers la page de CAS. J'ai vérifié qu'elle n'avait pas de compte et j'ai essayé le lien : j'ai eu droit à la même page. Je copie le lien ci-dessous comme cela vous pourrez tester.
https://epiga.episciences.org/reviewer/invitation/id/21777/lang/en
Merci d'avance pour votre aide !
Benoît

**Comment by devletech** [comment]
![Capture d'écran du 2023-03-13 10 45 59@2x](https://user-images.githubusercontent.com/20502173/224670534-46d2de55-b9ce-4949-90db-5c975758d57c.png)
Cela est normal : 
> Comme vous pouvez le voir sur la capture ci-dessous,  la personne a déjà un compte hors revue. Une fois connectée au serveur CAS, elle  pourra accepter et relire l’article. 
Merci à vous,
Djamel
