### ISSUE TITLE
[Feature request] Confirmation when closing the modal to compose an email?

### ISSUE THREAD

**Issue by a3nm** [CCSDForge/episciences#322]
When composing an email on the Episciences platform, it is easy to accidentally click "Close". This loses the contents of the email without confirmation message. (It is especially confusing that, when clicking "Cc" to add people in Cc, clicking "Close" discards the message instead of going back to the window to edit the message.

Would it be possible to add a confirmation message when closing the email editor window, e.g., if the email being edited is non-empty?

Thanks!

**Comment by rtournoy** [comment]
- [ ] Opening CC to add people and closing with "Close" must not close the email
- [ ] Closing the email with "Close" must display a warning if a the body is not empty

**Comment by rtournoy** [comment]
Fixed in production
