### ISSUE TITLE
[Feature request] Pages génériques : modification d'intitulé

### ISSUE THREAD

**Issue by cbarthonnat** [CCSDForge/episciences#323]
**Page d'accueil / Homepage**
- remplacer "Homepage" par "Home" ;
- remplacer "Page d'accueil" par "Accueil".

**Charte d'éthique / Ethical charter**
- remplacer "Charte d'éthique" par "Charte éthique" (supprimer le d')

Merci :)

**Comment by rtournoy** [comment]
Fixed with release [v1.0.41](https://github.com/CCSDForge/episciences/releases/tag/v1.0.41)
