### ISSUE TITLE
[Feature request] correction page Settings (EN)

### ISSUE THREAD

**Issue by cbarthonnat** [CCSDForge/episciences#324]
Sur la page Settings, version EN (ex : https://epi-preprod.episciences.org/review/settings),
dans "Section choice", remplacer :
- "The contributors can’t choose a section" par "**C**ontributors can’t choose a section"
- "The contributors can choose a section" par "**C**ontributors can choose a section"
- "The contributors **has** to choose section" par "**C**ontributors **have** to choose **a** section".

**Comment by rtournoy** [comment]
fixed in v1.0.39.6
