### ISSUE TITLE
[Bug Report] Ability to accept a manually canceled invitation / possibilité d'accepter une invitation qui a été manuellement annulée

### ISSUE THREAD

**Issue by emperrin** [CCSDForge/episciences#325]
An editor had invited a reviewer to review a submission. Since he had not answered after more than a week, the editor canceled the invitation in the interest of quick processing. But then the reviewer accepted the invitation.
So, the system allows accepting an invitation after it has been canceled. 

Un éditeur a invité un évaluateur à examiner une soumission. Comme ce dernier n'a pas répondu, après plus d'une semaine, l'éditeur a annulé l'invitation afin d’accélérer le processus d'évaluation. L'évaluateur a ensuite accepté l'invitation.
Le système permet donc d'accepter une invitation après qu'elle a été annulée.

**Comment by rtournoy** [comment]
fixed in v1.0.39.6
