### ISSUE TITLE
Accept SWHID reference on Episciences platform for software artifact

### ISSUE THREAD

**Issue by MaudMed** [CCSDForge/episciences#326]
Add a "related material / software" (or equivalent) field in the submission form where the authors can enter the SWHID of a source code associated with the submitted paper.

Identical features for #327 

1. Use case 1st submission, on the submission form:
- [x]  add a "Select" to choose the type of related material (Dataset ; Software ; Publication)
- [x] add a text input to input (HAL identifier ; SWHID ; DOI)

2. Use case submission in case of revision of previous submission: 
- [x] on the submission form inherit the previous entries by the user, allow the user to delete and add new (HAL identifier ; SWHID ; DOI) user the form designed at step 1.

3. Use case on the administration page of a submission after the initial submission form
- [x]  Allow the authors to add a "related material / software" using use case 1. Feature only allowed before the publication of the article
- [x] Allow the editors of the article to to add a "related material / software" using use case 1. Feature allowed at any step of the publication process.

### Metadata to Store and Display on the web page of the article:

- If HAL identifier:
  Get metadata from HAL codemeta.json example: https://hal.inrae.fr/hal-02828543/codemeta

- If SWHID OR URL:
  Try to get metadata from codemeta.json
  if no codemeta.json is present:
   Add message:
   A [codemeta.json](https://codemeta.github.io/user-guide/) file was not found. We were not able to automatically retrieve 
  metadata for this software.
  else if codemeta.json is present:
   Retrieve and persist in DB.

**Comment by rtournoy** [comment]
Fixed with release [v1.0.41](https://github.com/CCSDForge/episciences/releases/tag/v1.0.41)
