### ISSUE TITLE
Volume pagination nav has inconsistent target urls

### ISSUE THREAD

**Issue by t-wissmann** [CCSDForge/episciences#33]
On the 'regular volume' browser on lmcs.episciences.org, the page navigation on the bottom of https://lmcs.episciences.org/browse/regularissues/page/2 has inconsistent urls. The links to page *n* are `https://lmcs.episciences.org/browse/regularissues/page/`*n* as expected, but the links `«` and `»` point to `https://lmcs.episciences.org/browse/volumes/page/1` and `https://lmcs.episciences.org/browse/volumes/page/3` (being on page *n* the `»` points to `/browse/volumes/page/`*n+1*), which both lead to 404-pages.

**Comment by rtournoy** [comment]
thank you! the fix should appear online soon

**Comment by t-wissmann** [comment]
Thanks!
