### ISSUE TITLE
Add a reference to the archived software artifact on exported metadata (OpenAIRE, Crossref, etc.)

### ISSUE THREAD

**Issue by MaudMed** [CCSDForge/episciences#330]
Record's exported metadata (harvestable through an API) should include a reference to the archived software.

- [x]  Crossref
- [x] OpenAIRE
- [x] TEI

**Comment by rtournoy** [comment]
Fixed with release [v1.0.41](https://github.com/CCSDForge/episciences/releases/tag/v1.0.41)
