### ISSUE TITLE
Request from the authors submitting a manuscript that they first archive the associated source code in SWH

### ISSUE THREAD

**Issue by MaudMed** [CCSDForge/episciences#333]
Add a section in the Episciences documentation to explain to authors that, if they have a related source code, it must be first (self-) archived in SWH and then linked with the paper’s submission (via the Episciences interface -cf. issue 326).

References:

- https://www.softwareheritage.org/save-and-reference-research-software/
- https://www.softwareheritage.org/2020/05/26/citing-software-with-style/

**Comment by rtournoy** [comment]
https://jtcam.episciences.org/page/submission
