### ISSUE TITLE
Add on the documentation or/and requirements of the Episciences journal how to add a reference to the source code on the article's pdf

### ISSUE THREAD

**Issue by MaudMed** [CCSDForge/episciences#334]
Add a section (in the Episciences documentation and in each journal guidelines) dedicated to referencing the source code in the article's pdf, so that the journals running on the platform know how to expose related software artifacts directly in the article's pdf (via a stylesheet).

**Comment by rtournoy** [comment]
Documentation: https://doc.episciences.org/software/
Example for a journal citing the documentation: https://jtcam.episciences.org/page/submission
