### ISSUE TITLE
[Feature request] LMCS: Add 2 statistics data

### ISSUE THREAD

**Issue by CathScott** [CCSDForge/episciences#339]
Add statistics in the Statistics module for :   
- Number of revisions requested
- Number of revisions received

**Target for 2024:** 
Key statistics published annually:
   - Number of submissions
   - Number of reviews requested
   - Number of reviews received
   - Number of accepted submissions
   - Average time between submission and publication.

[cf° RT Ticket URL: https://support.ccsd.cnrs.fr/Ticket/Display.html?id=170781]

**Comment by rtournoy** [comment]
See Also #208

**Comment by rtournoy** [comment]
moved to #208
