### ISSUE TITLE
[Feature request] "Consult the article webpage"

### ISSUE THREAD

**Issue by a3nm** [CCSDForge/episciences#342]
Hi,

I was pointed out a minor imperfection of the platform: on the pages of articles, e.g., https://theoretics.episciences.org/10185, there is a button "Consult the article webpage" (see screenshot).

![2023-03-29-185923_3600x1200_scrot](https://user-images.githubusercontent.com/843551/228614744-eb505334-ddb3-4057-9134-6150711156ee.png)
 
This is a bit confusing, because https://theoretics.episciences.org/10185 is the article webpage, at least on the journal. Maybe a clearer caption could be "Consult the article's arXiv page", or "Consult the article's $REPOSITORY page" depending on what is the underlying repository.

Thanks!

**Comment by devletech** [comment]
it's done and online
