### ISSUE TITLE
Submit (new temporary version) button not visible in Safari

### ISSUE THREAD

**Issue by 497e0bdf29873** [CCSDForge/episciences#343]
In the '_Submit a new temporary version_' dialog, the submit button is not visible in Safari (after adding two documents). It is visible in Firefox.

**Comment by HeleneLowinger** [comment]
HL va tester

**Comment by HeleneLowinger** [comment]
Hi, 
I've tested with Safari (v.15.6.1) and I can submit temporary version (3 times for the same article, no problem). (see screenshots). Could-you tell us more? 
![Capture d’écran 2023-05-24 à 15 13 54](https://github.com/CCSDForge/episciences/assets/91547400/4c9ac4c6-7447-40bc-8f01-9c9db274ad2f)
![Capture d’écran 2023-05-24 à 15 17 01](https://github.com/CCSDForge/episciences/assets/91547400/1c217ee5-29b1-4f0d-adb5-e910c0ed1ecd)

**Comment by Arolland-math** [comment]
Without any news from you, and having found no bug in safari, we close this ticket.

**Comment by 497e0bdf29873** [comment]
Now, trying to upload a revision, the 'Upload temporary version' dialog is squished this badly in safari:

<img width="1290" alt="Screenshot 2023-07-11 at 8 42 04" src="https://github.com/CCSDForge/episciences/assets/96944487/f38b1486-c48d-42ae-95c3-64006e8574e3">

**Comment by clason** [comment]
I see the same issue in Safari Version 16.6 (18615.3.12.11.2).

**Comment by devletech** [comment]
related to #361 [Fixed]:  https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#fixed
