### ISSUE TITLE
[Feature request] Formatted files available on the contributor account

### ISSUE THREAD

**Issue by benoit-claudon** [CCSDForge/episciences#351]
When an article (existing as an arXiv version) is accepted and when it is formatted by the journal, the final files are sent through the editorial system "copy editing by the journal completed, ask for the final version". I recently had the case (epiga, permanent id 9626) where the mail was not received by the contributor (it was not even in the spam).
It would be interesting to access these files on the EpiGA account. I have just checked and they are not availlable: the only thing the contributor can do is submit a new version.
Best,
Benoît

**Comment by benoit-claudon** [comment]
actually there is no "mailing history" at the bottom of the page when 
I'm logged as the author... I was surprised by this fact because I 
thought it was always present on the admin page but I double checked and 
I saw no history neither a field where the formatted files could be stored.

Le 30/05/2023 à 16:21, a3nm a écrit :

**Comment by a3nm** [comment]
I'm also confused by this comment -- why are you logging in as the author when you want to consult the mailing history? This should be accessed as the admin.

I now suspect that your request was that *authors* should be able to consult the files in question on the Episciences platform themselves. This makes sense -- what I'm saying is only a workaround that an admin could use.

(That said, on a more general note, I think it would also be sensible if the platform gave to all users an access to the history of the mails that they received.)

**Comment by benoit-claudon** [comment]
I logged in as the contributor to understand what he/she was able to 
see. And yes it was my request (but maybe not very well formulated): it 
would be nice that the author can access to the formatted file inside 
from his/her account.

Le 30/05/2023 à 19:43, a3nm a écrit :

**Comment by devletech** [comment]
Fixed: https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#changed
