### ISSUE TITLE
Augmenter la taille du champ adresse Mastodon / Increase the size of the Mastodon address field

### ISSUE THREAD

**Issue by CathScott** [CCSDForge/episciences#352]
(Cf° RT #187373﻿)
Actuellement, il semble que le champ adresse de Mastodon est limité à 30 caractères. Serait-il possible d'augmenter sa capacité? Merci
/
At the moment, it seems that Mastodon's address field is limited to 30 characters. Would it be possible to increase its capacity? Thank you.

**Comment by rtournoy** [comment]
It seems that 255 chars in correct:
https://docs.joinmastodon.org/methods/accounts/#:~:text=By%20default%2C%20max%20255%20characters

`fields_attributes[:index][value]
String. The value of the profile field. By default, max 255 characters.
`
