### ISSUE TITLE
Improvement of the referees user experience

### ISSUE THREAD

**Issue by emperrin** [CCSDForge/episciences#360]
[ticket https://support.ccsd.cnrs.fr/Ticket/Display.html?id=189916 - LMCS]

Apparently a referee has to login and then say 'yes' again after he has already said 'yes' to a review invitation : 

I followed the link in the email which took me to a choice of accept or reject.  I clicked on accept but it does not end there!  It then takes you to the login page and if you login it asks you again.  I did not realize that I had to login and click accept again.  It actually gave me an authentication error but then logged me in anyway!  I do have an acknowledgement email now saying that I have accepted.

**Comment by rtournoy** [comment]
Fixed in 1.0.40.15 - 2023-09-15
