### ISSUE TITLE
Temporary version is assigned new identifier

### ISSUE THREAD

**Issue by clason** [CCSDForge/episciences#363]
At JNSAO, an author has recently submitted a revision as a temporary file (jnsao:10433, you will remember ;)). However, the revision has been assigned a new ID and thus a new management page, so that the previous reviewers are not available for inviting.

Is this deliberate? And if so, can that be changed, since it adds unwelcome friction to the editor workflow?

**Comment by Arolland-math** [comment]
testé le 4/10/23 : les relecteurs de la première version sont bien disponibles même si on n'a pas coché la case "assigner les mêmes relecteurs" dans le cas d'une version 2 et dans le cas d'une version temporaire.
