### ISSUE TITLE
[Feature request] switching the author process for an Episcience article in V2

### ISSUE THREAD

**Issue by didierjosselin** [CCSDForge/episciences#369]
Hello,
Many authors are upset to proceed in 4 steps their submission for V1 & V2 : HAL + Episcience Journal.
It would be more efficient if, once the paper in version 1 in the Episcience Journal is in its final reviewed version, if the Journal manager would be and to pass it back to HAL in its version 2 and then take care of this last procedure.
Il would be possible in the agreement between the journal and the author(s) if it is specified that, the authors agree the editor to send the V2 version directly to HAL and then proceed in its final publication.
Regards.
Didier.

**Comment by cbarthonnat** [comment]
Une amélioration pour faciliter le dépôt dans Episciences depuis HAL est en cours de développement
