### ISSUE TITLE
Automatic reload pages after changes

### ISSUE THREAD

**Issue by CathScott** [CCSDForge/episciences#372]
(Cf° Ticket RT#191262)

- Changing some data of a paper (e.g the volume to which it is assigned) doesn't update the information that is visible on the page. 
- After manually reloading the page, the paper is then shown correctly, 

 --> would it be possible to have a systematic reload after any such change in the database?

**Comment by rtournoy** [comment]
Fixed with release [v1.0.41](https://github.com/CCSDForge/episciences/releases/tag/v1.0.41)
