### ISSUE TITLE
Importer l'orcid & affiliations depuis zenodo

### ISSUE THREAD

**Issue by laurentromary** [CCSDForge/episciences#374]
Quand un article est soumis via Zenodo, il faudrait importer les orcid pour les auteurs qui l'ont renseigné.

**Comment by devletech** [comment]
idem pour les affiliations

**Comment by rtournoy** [comment]
Fixed with release [v1.0.41](https://github.com/CCSDForge/episciences/releases/tag/v1.0.41)
