### ISSUE TITLE
Article versions in wrong order for one article

### ISSUE THREAD

**Issue by t-wissmann** [CCSDForge/episciences#38]
On the [administratepaper page for the lmcs article 7537](https://lmcs.episciences.org/administratepaper/view/id/7537) the paper versions appear in wrong order:
![image](https://user-images.githubusercontent.com/9048813/124130618-4350c280-da7f-11eb-8eae-7e62c3cb5970.png)

However, I couldn't find a single other paper where the versions are listed in the wrong order. If only this article is affected, then please feel free to just close and ignore this issue, it is a very minor thing anyway :-) I only wanted to have it mentioned/documented for the case that something similar happens in another article.

**Comment by rtournoy** [comment]
It has been fixed today with a new small release : https://github.com/CCSDForge/episciences/blob/v1.0.12/CHANGELOG.md

The wrong column was used to sort the versions, but ... eventually it was correct in most cases.

Thanks for opening this issue!
