### ISSUE TITLE
[Bug Report] [JTCAM] OpenCitations entries with special characters/ORCID identifiers wrongly reported

### ISSUE THREAD

**Issue by mlegr** [CCSDForge/episciences#380]
Accentuated characters and apostrophes in OpenCitations entries are incorrectly reported, see [this JTCAM paper](https://jtcam.episciences.org/7052):

Doitrand, Aur**ĂŠ**lienORCID-iD; Henry, Ronan; Lube, TanjaORCID-iD; Meille, SylvainORCID-iD, 2021, Size Effect Assessment By Weibull**â**s Approach And The Coupled Criterion, Engineering Fracture Mechanics, 256, pp. 107979, [10.1016/j.engfracmech.2021.107979](https://doi.org/10.1016/j.engfracmech.2021.107979).

ORCID identifiers are also faulty in

Collins-Craft, Nicholas Anton, 0000-0003-2510-137; Bourrier, Franck, 0000-0001-7012-818; Acary, V., 2022, On The Formulation And Implementation Of Extrinsic Cohesive Zone Models With Contact, Computer Methods In Applied Mechanics And Engineering, 400, pp. 115545, [10.1016/j.cma.2022.115545](https://doi.org/10.1016/j.cma.2022.115545).

The first issue was not observed in other Episciences journals

**Comment by rtournoy** [comment]
Hello, this is how the metadata comes from OpenCitations. It will be fixed in the next release, we are still using OpenCitations to obtain the citations identifiers, but have moved to OpenAlex to obtain the citation text.

**Comment by rtournoy** [comment]
I have created an issue at OpenCitations about that in June 23

**Comment by rtournoy** [comment]
Fixed in v.1.0.41, Citations come from OpenCitations, then the metadata now comes form OpenAlex
