### ISSUE TITLE
[Feature request] Make revision deadlines mandatory

### ISSUE THREAD

**Issue by a3nm** [CCSDForge/episciences#388]
The Episciences platform supports setting a deadline for revisions of articles by authors, but this is currently optional, so editors typically do not use it.

Would it be possible to have a journal setting (just a checkbox) to require that a deadline is given with revision requests?

Thanks!

**Comment by rtournoy** [comment]
We will make the deadline mandatory for everyone, it makes sense to have a deadline anyway when you require a feedback

**Comment by clason** [comment]
I wouldn't like to have that; it can add unreasonable friction to contributors. If it's enabled by default, at least let editors set and disable the deadline.

**Comment by rtournoy** [comment]
> I wouldn't like to have that; it can add unreasonable friction to contributors. If it's enabled by default, at least let editors set and disable the deadline.

ok thanks, then we will not make it mandatory ;)

**Comment by devletech** [comment]
done
![Capture d'écran du 2024-01-24 17 44 54@2x](https://github.com/CCSDForge/episciences/assets/20502173/61411b09-da6c-4088-a0ac-abc0854f6145)
