### ISSUE TITLE
[Bug Report] [JTCAM] Wrong metadata automatically added on HAL

### ISSUE THREAD

**Issue by mlegr** [CCSDForge/episciences#390]
For accepted JTCAM papers stored on HAL, the "volume" metadata seems to be randomly updated by some strange mechanism. The faulty information has to be suppressed manually on a regular basis. An example is shown below but there are multiple other ones. It looks like there is a bug somewhere in the interface.

![JTCAM_bug](https://github.com/CCSDForge/episciences/assets/92648586/03a5dcbc-0fc4-4c60-8335-e52096db62ff)

**Comment by rtournoy** [comment]
Fixed with a new notification system based on [COAR Notify](https://notify.coar-repositories.org/)
