### ISSUE TITLE
[Bug Report] Untranslated text on dashboard

### ISSUE THREAD

**Issue by a3nm** [CCSDForge/episciences#392]
Hi,

On the TheoretiCS dashboard for an author https://theoretics.episciences.org/paper/submitted/lang/en/status/15 we see the following text, which is in French even though the rest of the interface is in English: Liste des articles que j'ai proposés à "TheoretiCS".

Would it be possible to translate this text?

Many thanks!

**Comment by rtournoy** [comment]
Hello,
thanks! it is now fixed [with other changes listed here](https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#104020---2023-10-31)
