### ISSUE TITLE
[Feature request] Possibility to send a minor corrected version of article through interface

### ISSUE THREAD

**Issue by vyastreb** [CCSDForge/episciences#396]
Hello,

The problem is the following. 
When the corresponding author of a paper is asked to provide only minor revision then there is no need to polluate the HAL with another version which is only slightly different from a previous one. So at JTCAM we would like to have a possibility to reply 
with an attachment of a new version.

Currently, in "Answer this request" we only have:
- "Contact without sending a new version"
- "Answer without any modification"
- "Upload a new version"

![Screenshot from 2023-11-20 16-09-52](https://github.com/CCSDForge/episciences/assets/63041295/339d403c-f3c3-4014-9ad8-44078cbc5d49)

So, it would be great to have another option
- "Send a new version as an attachment (case of minor revision)"

Thanks in advance for consideration,
VY for JTCAM TB

**Comment by clason** [comment]
You can enable this in your journal's settings:

<img width="523" alt="Screenshot 2023-11-20 at 16 16 56" src="https://github.com/CCSDForge/episciences/assets/2361214/46a9e11b-7e2b-422c-8b46-c4766d2f0a88">

Or is the request specifically to enable this for minor revisions only, while still forbidding it (why?) for major revisions?

**Comment by vyastreb** [comment]
Perfect! Thank you very much for such a prompt reply!
I've activated this option and tested! 
Thank you again!

No, no need to have this option for minor revisions only.

**Comment by vyastreb** [comment]
Hello!
Finally, we need to reopen this issue/request.
The problem is the following: when we use this option
"Contributors can answer revision requests with a temporary version"
on the later stage, the authors anyway need to load a new version on open archive, otherwise the editor cannot proceed to the next stage, for example, accept the paper and ask for sources... 
So we really need a new functionality that the authors can address the minor revision which could be shared with the editor and all the reviewers.

Thank you for your consideration!

**Comment by vyastreb** [comment]
Hello!
Finally, we need to reopen this issue/request.
The problem is the following: when we use this option
"Contributors can answer revision requests with a temporary version"
on the later stage, the authors anyway need to load a new version on open archive, otherwise the editor cannot proceed to the next stage, for example, accept the paper and ask for sources...
So we really need a new functionality that the authors can address the minor revision which could be shared with the editor and all the reviewers.

Thank you for your consideration!

**Comment by clason** [comment]
No, sorry, that is not true. Only the very last step, acceptance requires an upload -- but that would not be a revision.

**Comment by a3nm** [comment]
Yes, our experience with TheoretiCS is that temporary versions work fine: they ensure that authors don't need to resubmit on a repository for each single revision, but at the very end the final version must still be deposited to the repository, which we think is acceptable.

**Comment by rtournoy** [comment]
Thanks to everyone for the contributions :)

Since the beginning of December [V1.0.41](https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#1041---2023-11-27) :
- "Contact without sending a new version" You may now add a file, Status will not change
- "Answer without any modification": You may now add a file, Status will change

See also: #313 

Is it OK for you @vyastreb ?

**Comment by vyastreb** [comment]
Thank you very much @rtournoy  ! I've tested, it works and it is what was needed! 
Sorry for the lack of reactivity!

**Comment by rtournoy** [comment]
Great thanks everyone!

**Comment by vyastreb** [comment]
@rtournoy, after some thinking, I think that the titles of the options available to the author are slightly misleading.
"Contact without sending a new version" allows to send a new version, maybe a more accurate version would be 
"Reply without deposing a new version" or "Respond without a new upload".

**Comment by mlegr** [comment]
I agree with @vyastreb. The list of options is slightly misleading, at least for option 2 "Answer without any modification" (You may now add a file, Status will change). Status will change, which is great, and a file can be added, which is great as well but the title is wrong because changes are listed in the attached file. So "Respond without a new upload but with an attachment" would make more sense (at least for JTCAM). Thank you.
