### ISSUE TITLE
[Bug Report] "Update metadata" seems to delete existing metadada

### ISSUE THREAD

**Issue by mlegr** [CCSDForge/episciences#408]
With the new (and nice!) categories "Linked publications - datasets - softwares" recently implemented, the "Update metadata" option in the management page of a paper seems to delete the existing metadata which was listed in the box "Publications" (which no longer exists). The deleted metadata should then be added manually. This is probably an undesired behaviour.

**Comment by rtournoy** [comment]
Yes this is an undesired behaviour, can you give us an example please?

**Comment by mlegr** [comment]
As a JTCAM user with admin rights, if I click on "Update metadata" of paper [https://jtcam.episciences.org/9194](https://jtcam.episciences.org/9194), the current link to Zenodo in the "Publications" tab will be deleted.

**Comment by rtournoy** [comment]
The fix has been released today with : https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#10412---2023-12-05
