### ISSUE TITLE
[Feature request] "References" tab: possibility to add identifiers other than DOI

### ISSUE THREAD

**Issue by mlegr** [CCSDForge/episciences#409]
The new "References" tab associated to each paper is great. However, only DOI are accepted as identifiers. It would be great to add some flexibility here so that other identifiers (oai, arxiv...) can also be mentioned (manually if needed), in the same way as what was made possible on HAL with the GROBID engine.

**Comment by rtournoy** [comment]
TODO:

- [ ] @JcharlesCCSD please add `https://doi.org/` only when the PID matches a DOI

**Comment by rtournoy** [comment]
See also #413

**Comment by rtournoy** [comment]
> Actually it is possible to add any type of identifier, including URLs, the label DOI is misleading and will be changed to something more generic

The label has just been updated as "DOI, URL, ..."

**Comment by rtournoy** [comment]
Thanks for the report, all fixes are now in production version

**Comment by mlegr** [comment]
We can now indicate URL other than DOI but we cannot indicate both a DOI and another URL. Could this be implemented? At JTCAM, we try to promote Open Access and, in the bibliography, we indicate when possible both DOI and  HAL/arxiv (or equivalent) identifiers. Thanks!
