### ISSUE TITLE
[Bug Report] Faulty DOI links and Journal names in OpenAlex entries

### ISSUE THREAD

**Issue by mlegr** [CCSDForge/episciences#410]
Please see the screen shot below showing the issue defined in the title of the report.

![OpenAlex](https://github.com/CCSDForge/episciences/assets/92648586/ccfaf1be-fc30-46d6-8590-c5dcee4c456f)

**Comment by rtournoy** [comment]
thank you for the bug report

- [ ] a fix for the DOI mixed with the omid/be is ready to be shipped on 4 Dec. 23
- [ ] The journal name is a new problem, we're currently looking at this problem

**Comment by rtournoy** [comment]
fixed in production
