### ISSUE TITLE
[Bug Report] Volume page does not show volume description anymore

### ISSUE THREAD

**Issue by t-wissmann** [CCSDForge/episciences#414]
**Describe the bug**
The content of the `description` field of a volume is not shown on 
`/volume/view/id/⟨vid⟩`

**To Reproduce**
* Take a volume with a non-empty `description` metadata field, e.g.:
  - on https://lmcs.episciences.org/volume/edit?id=738 ("Volume 19, Issue 2"), the description is `2023`
  - on https://lmcs.episciences.org/volume/edit?id=310 (CALCO 2017 SI) the description is `Editors: Filippo Bonchi, Barbara König`
* Go to the respective `/volume/view/id/⟨vid⟩` and see that it is not shown (also not in the html source):
  - https://lmcs.episciences.org/volume/view/id/738
  - https://lmcs.episciences.org/volume/view/id/310
* Bonus-Step (only for the regular but not the special issue volume): the description is shown in the volume browser: https://lmcs.episciences.org/browse/regularissues (see the `2023` below "Volume 19, Issue 2")

**Expected behavior**
I expect that a volume's description is visible on the volume's page.

**Additional context**
We used the description field to list the editors of special issue volumes, thus I know the description was shown there before and it seems to me that the description was dropped by accident.

**Comment by rtournoy** [comment]
thanks for nice bug report, it is fixed in production, please have a look and re open if needed

**Comment by t-wissmann** [comment]
Thanks! That was extremely quick, I'm impressed :-)
