### ISSUE TITLE
[Feature request] [JTCAM] Identifiers other then SWHID for Software solutions

### ISSUE THREAD

**Issue by mlegr** [CCSDForge/episciences#417]
The new _Softwares_ tab is great. However, the accepted identifiers seem to be limited to SWHID since the string `https://archive.softwareheritage.org/` is automatically appended to the provided link. Could other identifiers such as DOI or even HDL be accepted as well? See the example of paper [JTCAM12602](https://jtcam.episciences.org/12602) to see what currently happens.

**Comment by rtournoy** [comment]
Thanks creating the issue, even if a SWHID is recommended, other Identifiers are now supported. It has fixed the issue with [](https://doi.org/10.46298/jtcam.11056) . I have removed the duplicate DOI on the page by the way
