### ISSUE TITLE
[Feature request] [JTCAM] Manually edit `datasets, Software, Publications` categories

### ISSUE THREAD

**Issue by mlegr** [CCSDForge/episciences#418]
We take paper [JTCAM12218](https://jtcam.episciences.org/12218) as an example. The automatically extracted metadata always falls in the category _Publications/Other_. This is a bit annoying when the metadata is concerned with _Software solutions_ or _Datasets_. It would be nice to have the possibility to be able to manually edit/suppress the categories.

![categories](https://github.com/CCSDForge/episciences/assets/92648586/35be35b4-2d78-4095-ad92-fb294575c502)

**Comment by rtournoy** [comment]
fixed in production
