### ISSUE TITLE
Soumission automatique d'un preprint depuis Hal

### ISSUE THREAD

**Issue by HeleneLowinger** [CCSDForge/episciences#422]
- [x] S'il y a une demande de modification d'une soumission, l'auteur soumet une nouvelle version sur Hal ; il coche à nouveau pour soumettre automatiquement vers la revue (c'est déjà pré-rempli s'il l'a déjà choisi pour la version initiale) : OK. Mais il ne se passe rien sur la revue quand ce document est modéré sur Hal, il reste sur la revue " en attente de modification".

> https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#changed

- [x] Pour les modérateurs sur Hal, il faudrait que es articles soient identifiables facilement pour être traités en priorité (c'était aussi un des besoins initiaux). Comme pour Arxiv, il faudrait qu'un "label" ou message spécifique soit ajouté dans la colonne "document" (ou toute autre solution.

- [x]  L'auteur ne voit pas qu'il a proposé son document à une revue Episciences (son article, ou une version particulière de cet article) ; il pourrait y en avoir une trace quelque part...

**Comment by cbarthonnat** [comment]
Sur les mails aux déposant-es, voir côté HAL

**Comment by rtournoy** [comment]
autres traitements côtés HAL
