### ISSUE TITLE
[Feature request] Coquilles en pied de page des sites revues

### ISSUE THREAD

**Issue by cbarthonnat** [CCSDForge/episciences#423]
Deux coquilles dans le pied de page des revues m'ont été signalées :
- Technical support Email => Technical support (le terme Email est superflu) ;
- Term Of Use => Terms Of Use (il manque le s final à TermS, pourtant bien présent dans l'URL).

Les modifs sont à faire en prod et en pré-prod.

Merci :)

**Comment by rtournoy** [comment]
The typo Term Of Use => Terms Of Use  has been fixed
