### ISSUE TITLE
[Feature request] Editorial Staff members : amélioration affichage des données

### ISSUE THREAD

**Issue by cbarthonnat** [CCSDForge/episciences#424]
Quelques propositions pour améliorer l'affichage des données sur la page https://ops-preprod.episciences.org/review/staff

- icône Orcid à mettre à côté du nom
- lien vers une page perso à mettre sur l’ensemble de l’url et non seulement sur l’icône (difficilement cliquable)
- idem pour le lien ROR

Merci :)

**Comment by rtournoy** [comment]
ajout d'un lien sur URL ROR

**Comment by devletech** [comment]
@cbarthonnat, le lien ci-dessous fonctionne à nouveau  avec les modifs mentionnées dans le ticket

>  https://epi-preprod.episciences.org/review/staff

**Comment by rtournoy** [comment]
en ligne
