### ISSUE TITLE
[Feature request] Emails get stored as comments for each paper

### ISSUE THREAD

**Issue by nathanael-fijalkow** [CCSDForge/episciences#429]
The issue: a lot of discussions by editors about articles are done by email, and are not recorded in the system, which makes follow-up very difficult (emails get lost, and not all the people concerned are always copied). A lot of time and effort is wasted asking "did you send a reminder to this reviewer / did you take a decision" etc.

My suggestion: an alias is automatically created for each paper, for example theoretics-1132@episciences.org 
Then, each time an editor sends an email to this alias, the email (and its replies) are automatically added as comments on the paper. In practice, editors just need to add the alias each time they correspond by email.

Similarly, when sending some notifications about a paper, we add "reply to: theoretics-1132@episciences.org", so that any replies are stored as comments (instead of lost, as is the case now).

Thanks!

**Comment by rtournoy** [comment]
It requires some investigation on our side, we would need an API to handle the creation of email aliases, etc. Maybe we should improve the features on the platform to avoid emails outside the platform?

**Comment by rtournoy** [comment]
We are not in a position to do this at the moment due to technical constraints on with email server, we keep the idea if are able to use an appopriate list server, it is a project we have
