### ISSUE TITLE
[Feature request] A link from review to management page

### ISSUE THREAD

**Issue by nathanael-fijalkow** [CCSDForge/episciences#431]
As Editor: 

I'm looking at a review I wrote, on a page
https://YYYYY.episciences.org/paper/rating?id=XXXX
And I don't see a simple way of accessing the management page:
https://YYYYY.episciences.org/administratepaper/view?id=XXXX

Thanks,
Nath

**Comment by rtournoy** [comment]
We're not sure to understand, can you please give more explanation, or share an example via the email address of the support?

**Comment by rtournoy** [comment]
@nathanael-fijalkow can you please check on your pre-production version if that suits yours needs?

**Comment by davidjpurser** [comment]
Hi, Nath is no longer our managing editor, but indeed I think the new button on pre-prod is exactly what he meant, thanks!

**Comment by HeleneLowinger** [comment]
OK
