### ISSUE TITLE
[Feature request] Statistics: add an option to ignore statistics before a given date

### ISSUE THREAD

**Issue by rtournoy** [CCSDForge/episciences#434]
For existing journal with content imported from a previous publication platform, we need to be able to ignore submissions before the journal actually start the whole publishing process on the platform. For instance the acceptance rate is wrong when considering all the years of a journal with imported content. It will artificially be high because we only have information about accepted and published papers, not about refused papers. Articles rejected in the years preceding the journal's arrival on the platform are not imported; only those that are published are imported.

On the journal settings, add a new setting:
"Start statistics after : [date field YYYY-MM-DD]"

when the field is not empty with a valid date add a parameter to the API query to get the stats after the date provided as a parameter

Not stats will be provided for the years before this date on the journal's statistics page.

**Comment by devletech** [comment]
https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#v10417---2024-02-12
