### ISSUE TITLE
[Bug Report] Browse by authors or date: wrong links on the titles

### ISSUE THREAD

**Issue by mlegr** [CCSDForge/episciences#435]
When searching for articles using the "Browse by date" or "Browse by author" feature, the hyperlinks on the titles do not point to the correct website.  See screenshot below:

![mouseover](https://github.com/CCSDForge/episciences/assets/92648586/ffff4893-d34f-423d-b48f-f8958d6e25c9)

**Comment by rtournoy** [comment]
Thank you for the very clear bug report, we have fixed the bug
