### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by benoit-claudon** [CCSDForge/episciences#445]
Hi everyone,
on the page "articles to appear" (https://epiga.episciences.org/browse/accepted-docs#), I can see 10 articles (EpiGA) but on the dashboard there is 12 papers accepted and not yet published. This is not the first time I notice that. Moreover, the articles are sorted on a weird way on the above mentioned page: they should be sorted by date of acceptance and I see one paper that is not well placed.
Thanks for your help!
Benoît

**Comment by devletech** [comment]
all accepted articles are now displayed, sorted by descending acceptance date.
#https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#v10421---2024-03-12
