### ISSUE TITLE
[Bug Report] Paper list drops some spaces in abstracts

### ISSUE THREAD

**Issue by t-wissmann** [CCSDForge/episciences#446]
**Describe the bug**
In the abstracts of the papers listed in the volume browser and in `/browse/latest`, spaces are missing in some (very few) occassions.

This issue appears on any of these URLs:
* https://lmcs.episciences.org/browse/latest
* https://epijinfo.episciences.org/browse/latest
* https://lmcs.episciences.org/volume/view/id/925

The spaces are omitted very rarely, but it seems to be deterministic. If a paper is both in `/browse/latest` and volume 925, the mistakes are consistent. E.g. search for `withnameless` in [volume 925](https://lmcs.episciences.org/volume/view/id/925).

This mistake is in the HTML code sent by the server:
```
$ wget -q -O - 'https://lmcs.episciences.org/volume/view/id/925' | grep withname
                <blockquote class="abstract">By abstracting over well-known properties of De Bruijn's representation withnameless dummies, we design a new theory of syntax with variable binding andcapture-avoiding substitution. We propose it as a simpler alternative to Fiore,Plotkin, and Turi's approach, with which we establish a strong formal link. Wealso show that our theory easily incorporates simple types and equationsbetween terms.</blockquote>
```
(The snipped also contains further missing spaces: `Fiore,Plotkin` and `Wealso`)

The issue only persists in this paper list, because the abstract [on the correspondings paper's page id:13161](https://lmcs.episciences.org/13161) contains the space as expected, i.e. prints `with nameless`.

**To Reproduce**
* Go to any of the above URLs and look for words that are joined toghether even though they obviously should have a space inbetween them.
* On the pre-production server, run e.g.
```
$ wget -q -O - https://epijinfo.episciences.org/browse/latest |grep -E 'quotients[ ]*coalg'

                    <br/><blockquote><small>We present a generic partition refinement algorithm that quotientscoalgebraic systems by behavioural equivalence, an important task in reactiveverification; coalgebraic generality implies in particular that we cover notonly classical relational systems but also various forms of weighted systems.Under assumptions on the type functor that allow representing its finitecoalgebras in terms of nodes and edges, our algorithm runs in time$\mathcal{O}(m\cdot \log n)$ where $n$ and $m$ are the numbers of nodes andedges, respectively. Instances of our generic algorithm thus match the runtimeof the best known algorithms for unlabelled transition systems, Markov chains,and deterministic automata (with fixed alphabets), and improve the best knownalgorithms for Segala systems.</small></blockquote>                </p>


$ wget -q -O - https://epijinfo.episciences.org/697 |grep -E 'quotients[ ]*coalg' | head -n 1
<meta name="DC.description" content="We present a generic partition refinement algorithm that quotients coalgebraic systems by behavioural equivalence, an important task in reactive verification; coalgebraic generality implies in particular that we cover not only classical relational systems but also various forms of weighted systems. Under assumptions on the type functor that allow representing its finite coalgebras in terms of nodes and edges, our algorithm runs in time $\mathcal{O}(m\cdot \log n)$ where $n$ and $m$ are the numbers of nodes and edges, respectively. Instances of our generic algorithm thus match the runtime of the best known algorithms for unlabelled transition systems, Markov chains, and deterministic automata (with fixed alphabets), and improve the best known algorithms for Segala systems." >
```

**Expected behavior**
Show space characters from abstracts correctly. 

**Browser and Operating System (please complete the following information):**
Shouldn't matter (`qutebrowser v3.0.2` and `GNU Wget 1.21.4 built on linux-gnu.`)

**Comment by rtournoy** [comment]
Many thanks for the detailed bug report, it really makes a difference when trying to reproduce and fix the bugs :)

We have fixed the issue, the full change log for v1.0.42.3 is available here:
https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#v10423---2024-03-20
