### ISSUE TITLE
visibilité rapport pour auteur

### ISSUE THREAD

**Issue by Arolland-math** [CCSDForge/episciences#449]
epiga, article 11171
version 2 : https://epiga.episciences.org/paper/view?id=13256
l'auteur ne voit pas le rapport de relecture (visible par admin mais pas par auteur)

**Comment by devletech** [comment]
> ce n'est pas un bug

![Capture d'écran du 2024-03-20 14 37 24@2x](https://github.com/CCSDForge/episciences/assets/20502173/cc1d21d6-64c1-41ee-879f-8052ba68f2e4)

C’était lié à la suppression de la balise %%PAPER_RATING %% . Le message sauvegardé (voir la section **Demande de modifications** [visible par l'auteur]) ne contient donc pas cette information.

**Comment by devletech** [comment]
@Arolland-math c'est corrigé : https://epiga.episciences.org/paper/view/id/11171, https://epiga.episciences.org/paper/view/id/12633. 

> Sur la page de la version actuelle , voir ICI : https://github.com/CCSDForge/episciences/issues/169#issuecomment-1149657877
