### ISSUE TITLE
[Bug Report] French Année showing in search form

### ISSUE THREAD

**Issue by davidjpurser** [CCSDForge/episciences#451]
https://theoretics.episciences.org/search?q=* shows "Année" should be "Year"

The en translation file contains the French word:

https://github.com/CCSDForge/episciences/blob/540b97bdab17877ce768a4e229e6de419dbc7a82/application/languages/en/views.php#L969C1-L969C23 

`"year" => "Année",`
should be
`"year" => "Year",`

**Comment by rtournoy** [comment]
thanks ! fixed
