### ISSUE TITLE
[Bug Report] DOAJ fullText record gives a url that can't be accessed

### ISSUE THREAD

**Issue by davidjpurser** [CCSDForge/episciences#457]
The DOAJ export has a record
```<fullTextUrl format="pdf">https://theoretics.episciences.org/[someID]/pdf</fullTextUrl>```

This ID is the permanent/first version of the article, not the ID of the published version number (usually some versions later).

This URL does not work, and you will get an error message, "You do not have access to this article".
(Note, it does 'work' for administrators / those logged in with sufficient permission to see the first version - but the pdf will be of the first submission, not the final published version)

Either:
- The DOAJ link should be finalVersionID/pdf, or
- for published articles, permanentId/pdf should resolve to finalVersionID/pdf

The error applies to more than just TheoretiCS (e.g. also LMCS).

If the former is changed, then DOAJ will need to reimport every volume from all journals.

### Concrete Examples:

When logged out of episciences:

Click "Read online" at https://doaj.org/article/cb4cd745ba314618a150780a57398a3e or https://doaj.org/article/8d75bcff5dce43258cf965b28c393697

https://theoretics.episciences.org/export/volumesdoaj?vid=692 see ```<fullTextUrl format="pdf">https://theoretics.episciences.org/9608/pdf</fullTextUrl>``` should/could be https://theoretics.episciences.org/10814/pdf

**Comment by rtournoy** [comment]
The fix has not been deployed yet, it will be deployed after 2024-04-14

**Comment by rtournoy** [comment]
The fix is now in production
