### ISSUE TITLE
[Bug Report] Review not downloadable and not contained in notification email after update

### ISSUE THREAD

**Issue by smilius42** [CCSDForge/episciences#460]
Please have a look at lmcs #12339. 

The editor has allowed reviewer #1 to update his report. After that the editor has sent out the notification. But the link to the review is missing in the notification email to the authors. Also the author does not see a download button for that review on the article's web page in Episciences.  (The review is there because it is visible on the admin page of the submission for editors.)

Can you please fix that bug.

**Comment by devletech** [comment]
This is normal, the attached file is in the wrong place (criterion 3 is reserved for editors).
So I've manually changed the review by moving the file. The author will now be able to see the report.

**Comment by devletech** [comment]
@rtournoy
