### ISSUE TITLE
Swhid formating validation[Bug Report]

### ISSUE THREAD

**Issue by AlainMonteil** [CCSDForge/episciences#466]
**Describe the bug**
little bug when i copy and paste Swhid from Software heritage there a invisible space include, and so the iframe of software heritage don't appear but addition of softaware seem ok.
You may have an validation control of swhid see this page https://docs.softwareheritage.org/devel/swh-model/persistent-identifiers.html and if Swhid is not valid then open a message box "your swhid is not valid !" 
Best regards 
Alain

**To Reproduce**
1. Go to 'https://archive.softwareheritage.org/browse/origin/directory/?origin_url=https://github.com/sigsep/sigsep-mus-eval'
2. Click on 'permalink'
3. select the Swhid and copy
4. on episciences clic on add software
5. paste the swhid 
6. Iframe do't appear

**Comment by rtournoy** [comment]
Hello, thanks for the bug report, @JcharlesCCSD , can you please check that a trim is applied to the swhid value?
