### ISSUE TITLE
[Bug Report] average acceptance rate for our journal is not correctly calculated

### ISSUE THREAD

**Issue by smilius42** [CCSDForge/episciences#471]
It seems that the average acceptance rate for our journal is not correctly calculated. Currently, the statistics page shows:
Total : n articles (including m imported) | k published
and further below
Accepted articles a

The acceptance rate is currently calculated as (k+a)/n * 100
but it should be calculated as
(k + a - m)/(n-m) * 100

That is, the important articles should not taken into account when calculating the acceptance rate.

**Comment by rtournoy** [comment]
@smilius42 I'm just checking if the comment from @devletech and setting the new date parameter has solved the issue, or if we need to change something else?

**Comment by smilius42** [comment]
@rtournoy : Hi Raphaël, thanks for checking. Yes, setting the new date parameter has solved the issue. Even more, it's very useful to be able to see statistics e.g. for the last three years.
