### ISSUE TITLE
[Bug Report] English translation missing: Proposer dans le volume

### ISSUE THREAD

**Issue by davidjpurser** [CCSDForge/episciences#472]
When using a special issue access code, the choice of volume after entering the code is not translated into English.

Seen on LMCS

![SCR-20240503-jd9](https://github.com/CCSDForge/episciences/assets/1012323/90db0ad0-195f-477b-ac88-8a29b763531f)

**Comment by rtournoy** [comment]
It is fixed online, thanks!
