### ISSUE TITLE
Changing the publication date of a paper on Episciences when published

### ISSUE THREAD

**Issue by a3nm** [CCSDForge/episciences#50]
Hi,

I am from the journal LMCS, who wishes that the publication date of papers on Epsiciences corresponds to the date when the final version of the paper was made available on arXiv. Currently, our workflow is to try to publish the papers on the right date on Episciences, and ask for a manual fix if this fails.

It would be much better for us if the Episciences interface gave us (e.g., LMCS administrators) the possibility to change the publication date of any published article ourselves. Would that be possible?

Many thanks for your hard work!

**Comment by rtournoy** [comment]
Closed with v1.0.18 - 2021-09-30 online
