### ISSUE TITLE
[Bug Report] Can't change URLs / HTML in email templates

### ISSUE THREAD

**Issue by davidjpurser** [CCSDForge/episciences#507]
When editing email templates (/administratemail/templates) -> Select edit on some tempalte -> when trying to add a URL all of the text boxes are disabled and can't be changed (on a technical note, they don't seem to have the 'disabled' property, but nevertheless they can't actually be typed into). 

The same thing happens when you try to open the HTML source code, it shows it but can't be edited. 

I wonder if it's because the tinymce is in a modal window, so when you click the URL button or the HTML button its opening a second modal and that causes some confusion.

![SCR-20240531-mtl](https://github.com/CCSDForge/episciences/assets/1012323/ed12d3ca-9f4b-4f06-8d50-381bd540795d)

Problem occurs in Firefox and Chrome.

**Comment by rtournoy** [comment]
Thank you for the bug report and sorry for the inconvenience, a fixed has been pushed online

Please reopen if there's a problem.
