### ISSUE TITLE
Paramètre de notification de soumission

### ISSUE THREAD

**Issue by Arolland-math** [CCSDForge/episciences#508]
e vous écris parce que j'ai observé un comportement bizarre chez AFM: nous avons maintenant deux secrétaires d'édition (moi et Rob Lewis) et je voudrais que nous soyons les seuls à recevoir des mails automatiques lors d'une nouvelle soumission. C'est ce qui devrait se passer du moment que j'ai décoché la case "Editors in Chief" pour les "Notification settings" (voir pièce jointe).

Néanmoins, lorsque 
https://afm.episciences.org/administratepaper/view?id=13706
a été soumis, tous les éditeurs en chef ont été notifiés (voir en bas de la page de la soumission, où il y a la liste des messages envoyés). Pourriez-vous m'expliquer ce qui se passe et comment l'éviter?

AFM Filippo

**Comment by Arolland-math** [comment]
testé sur rmath2, effectivement, même si les cases redacteurs en chef et administrateur sont décochées ils reçoivent la notification de soumission

**Comment by devletech** [comment]
> Ce comportement est attendu si l'article n'a pas de rédacteur(s) assigné(s) (#188). 

> La solution consiste à forcer le choix du ou des rédacteurs au moment de la soumission : de cette manière, le système tiendra compte des paramètres de notification choisis.

**Comment by cbarthonnat** [comment]
J'ai également reçu la notification AFM pour l'article #13706 ; j'ai pour rôle "root" et "membre"

**Comment by Arolland-math** [comment]
On valide l'option que seuls les rôles cochés reçoivent la notification, indépendamment du fait que l'auteur choisissent ou non un rédacteur. Si on aucune option n'est cochée on envoie à tout le monde.

**Comment by devletech** [comment]
@Arolland-math  à tester stp

**Comment by Arolland-math** [comment]
testé le 6/06/24 : c'est ok !

**Comment by Arolland-math** [comment]
tu me diras quand c'est en prod ;-)
merci Djamel

**Comment by devletech** [comment]
@Arolland-math Ok, c'est en ligne

**Comment by Arolland-math** [comment]
AFM : on vient de recevoir une nouvelle soumission, et une fois de plus le serveur a envoyé un mail à tous le comité (tous les éditeurs en chief+éditeurs!). La chose était arrivée aussi le 2 septembre. J'ai coché la case comme quoi ces notifications devraient arriver seulement aux "editorial secretaries" (moi et Rob) précisément pour éviter de déranger tout le monde, mais visiblement cela ne marche pas. Dans ton mail du 6 juin tu me disais "le problème est résolu!" mais je crains que ce ne soit pas le cas...

**Comment by devletech** [comment]
Réparé [RT#221136]  @Arolland-math à retester STP.

**Comment by Arolland-math** [comment]
c'est good sur rmath2
