### ISSUE TITLE
[Feature request] Editor would be able to change the status to reviewed when he or she determines that the reviews received are enough to make a decision

### ISSUE THREAD

**Issue by emperrin** [CCSDForge/episciences#510]
Authors of submitted papers can view on the site the status of their paper. 
The status 'Reviewed'indicates to the authors that the reviews on the paper have been received, sometimes misleading them to think that the review process has been completed. 
However, in some cases, the handling editor would like to ask for additional reviews before s/he makes a decision on the paper.
Sometimes the decision of how many reviews are needed may depend on the outcome of the received reviews. For example, a review may be inconclusive and the editor may want to request another review, but if the authors see the paper as “reviewed”, they often start asking about why they haven’t received a decision.  

 It may be better to keep the status of a paper 'Under review' until the handling editor decides s/he received enough reviews to make a decision on the paper. Alternatively, if the status could only be seen by the editors but not the authors, then we wouldn’t have this issue.

**Comment by rtournoy** [comment]
We would need to add an option per journal, but in the meantime we can update the labels:

- [ ] 'Reviewed' => 'Reviewed pending editorial decision'
- [ ] 'Relu' => 'Relu en attente de décision éditoriale'

**Comment by emperrin** [comment]
I am reopening this ticket because the indication 'pending for editorial decision' was only a temporary workaround.
This issue occurs frequently with journals that require a minimum of one reviewer; the article switches to 'pending for editorial decision' as soon as the first review is received, leading authors to write in asking for updates on their manuscript : "It often happens that the authors email us after only one review has been received, because they see the message "Reviewed pending editorial decision" on the article page. But, as in this case, often the editors are waiting for a second review. I wish the authors didn’t see this message until the editor determines that the received reviews are enough information to make a decision."

See also : https://github.com/CCSDForge/episciences/issues/239

**Comment by rtournoy** [comment]
We will an additional message:
"A number of reviews have now been received, whilst others may still be ongoing."

**Comment by emperrin** [comment]
Cela ne répond pas à la demande des revues d'une plus grande flexibilité dans le nombre requis de relectures.
