### ISSUE TITLE
[Bug Report] Editor suggestions do not show when there is no comment message

### ISSUE THREAD

**Issue by davidjpurser** [CCSDForge/episciences#511]
If an editor makes an recommendation/suggestion to accept/refuse then the message does not show in the status box when there is no message.

### Desired vs Actual behaviour

Action: Editor makes a recommendation but leaves *no comment* (the box is not marked as required). 

Desired: Article status box on the administrate paper page should include a line "The editor (name) suggests to accept/reject this paper"

Actual: Nothing is in the Article status. The recommendation _can_ be seen in the history, but this is _not_ where we are used to looking (most editors leave a comment, then it is included in the article status box, but we miss it when they don't).

Please see support email from Mikaël Monet with a current example on TheoretiCS.

### Debug

This is because CommentsManager::getList has a filter which excludes messages which have no message or file. https://github.com/CCSDForge/episciences/blob/119cbaa1d4863853d66aad7901c10173ed2ea460/library/Episciences/CommentsManager.php#L175

The suggestions list to put on the adminsitrate paper page is found by EditorsManager::getEditorsSuggestionsByPaper from here:
https://github.com/CCSDForge/episciences/blob/119cbaa1d4863853d66aad7901c10173ed2ea460/application/modules/journal/controllers/AdministratepaperController.php#L778C1-L779C1

Which in turn calls: EditorsManager::getCommentsByTypes, which finally calls CommentsManager::getList Since this filters messages with no comment, then this does not show the editor recommendation.

Remark: the view is written in such a way as it expect to write the suggestion even when there is no message. Its just that the suggestions array is not populated due to the filter. https://github.com/CCSDForge/episciences/blob/119cbaa1d4863853d66aad7901c10173ed2ea460/application/modules/journal/views/scripts/administratepaper/view.phtml#L157

### Possible Fixes

1. Require a comment message when making a recommendation
2. Do not filter out comments with no message when getting the suggestions from the comment manager.

**Comment by devletech** [comment]
Fix is online, thank you
