### ISSUE TITLE
Optional date in revision deadline field?

### ISSUE THREAD

**Issue by CathScott** [CCSDForge/episciences#512]
(cf° Ticket RT : https://support.ccsd.cnrs.fr/Ticket/Display.html?id=214676)

When the editor sends a notification to the author, the “revision deadline” field is displayed as optional. Is this correct or a bug?
In fact, it would be preferable for the revision deadline to be indicated. This may explain why some automatic reminders are not sent/received if no deadline set is registered...

Thanks

**Comment by devletech** [comment]
This functionality is already available:  
![Capture d’écran du 2024-06-12 10-23-41](https://github.com/CCSDForge/episciences/assets/20502173/55c60e92-c2ac-4289-b3b5-030aff02c173)


> https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#added-3 [#388]

**Comment by smilius42** [comment]
Thanks for the clarification. That's great and exactly what we need. 

One question though: when this is switched on, it is possible for the handling editor to change the revision deadline after a minor/major revision request has been sent to the author? (E.g. in case the author later asks for a deadline extension.)

**Comment by devletech** [comment]
Yes:

![Capture d’écran du 2024-06-13 14-12-35](https://github.com/CCSDForge/episciences/assets/20502173/01988431-691b-40f5-bc04-eda86a7e52cb)

**Comment by smilius42** [comment]
Ok, thanks again. 

Is there also a way of entering a revision deadline later if an editor did not enter an (optional) revision deadline when sending out the revision request?

**Comment by rtournoy** [comment]
> Ok, thanks again.
> 
> Is there also a way of entering a revision deadline later if an editor did not enter an (optional) revision deadline when sending out the revision request?

yes the feature has just been added and pushed in production
