### ISSUE TITLE
[Bug Report] Liens vers la page des articles génèrent une erreur 404

### ISSUE THREAD

**Issue by emperrin** [CCSDForge/episciences#517]
**Please do not disclose any personal information (e.g. name of an author, reviewer, email addresses, etc.).**

Please use the support address if you need to mention personal data

**Describe the bug**
les liens vers la page des articles contenus dans les templates de mail "Assign a copy editor", "Formatting validation", "Final version answer" génèrent une erreur de type 404.
Le tag est  %25%25PAPER_URL%25%25
L'adresse générée par le lien est https://zimbra.inria.fr/zimbra/%25%25PAPER_URL%25%25

**Screenshots**
![404](https://github.com/CCSDForge/episciences/assets/99745326/7ed66a81-4dbc-4839-88bc-05e4badf7b41)

**Browser and Operating System (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version [e.g. 42]

**Additional context**

**Comment by devletech** [comment]
En rapport avec #507

**Comment by rtournoy** [comment]
templates corrigés
