### ISSUE TITLE
re-soumisison d'une V2 d'un article refusé en v1

### ISSUE THREAD

**Issue by Arolland-math** [CCSDForge/episciences#526]
Sur rmath2 : je teste pour epiga que lorsque l'on refuse un article, l'auteur peut  soumettre une V2 de ce même article. Après avoir confirmé que mon article a bien subi des modifs majeures ("replace"), tout va bien jusqu'à ce que je clique sur "submit" et là il me met une page d'erreur 

![Capture d’écran 2024-06-25 à 10 56 32](https://github.com/CCSDForge/episciences/assets/91665122/82607695-b256-495e-8ebc-f06b0a079181)

**Comment by devletech** [comment]
Corrigé
