### ISSUE TITLE
[Bug Report] articles submitted without a section when this parameter is mandatory

### ISSUE THREAD

**Issue by emperrin** [CCSDForge/episciences#527]
5 articles were submitted to DMTCS without a section when authors have to choose a section : 

dmtcs #13805 (20/06/24)
dmtcs #13804 (20/06/24)
dmtcs #13729 (06/06/24)
dmtcs #13633 (21/05/24)
dmtcs #13601 (16/05/24)

**Comment by HeleneLowinger** [comment]
I wonder if this is related to direct submission via Hal: doe it allow you to choose a section (or an editor) when it's mandatory ?
(I can not see if those articles were submitted via Hal or not, it's just an idea...)

**Comment by emperrin** [comment]
Yes, indeed, all these articles have been automatically transferred from Hal.

**Comment by emperrin** [comment]
There are currently two solutions:
- The editors-in-chief manually assign a section to the submitted articles.

- Automatic submission to the journal is no longer possible since the HAL repository.

**Comment by rtournoy** [comment]
Automatic submission to the journal is no longer possible from the HAL repository for this journal
