### ISSUE TITLE
[Feature request] Ask for other editors opinion: deselect all option.

### ISSUE THREAD

**Issue by davidjpurser** [CCSDForge/episciences#547]
Often when we want another editors opinion (Change Article Status > Ask for other editors opinion), we don't usually want to ask every editor but just one or two specific editors. Therefore it would be good if there was a button to unselect every editor quickly and then select only the ones we want with the existing checkboxes. 

(At the moment the default is that they are all selected, but then we would have to go one by one to deselect them all; this just leads to us sending the request outside the system).

Other journals may want to mostly ask everyone (I don't know), so it makes sense to either: be able to start from everyone and remove individuals, or start from no one and add individuals.

**Comment by devletech** [comment]
Fixed with release [v1.0.45.2](https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#v10452---2024-10-22)
