### ISSUE TITLE
[Feature request] corrections à apporter dans les paramètres au sujet des conflits d'intérêt

### ISSUE THREAD

**Issue by emperrin** [CCSDForge/episciences#555]
Dans les paramètres, ajouter les éditeurs en chef à la description du mode conflit d'intérêt :

Le mode conflit d'intérêts (CI) aura les effets suivants : toutes les informations non publiques concernant une soumission ne sont pas accessibles aux **éditeurs en chef** et aux éditeurs tant qu'ils n'auront pas déclaré l'absence de tout conflit d'intérêts.

This mode will have the following effects: all non-public information about a submission is not accessible to an **editor in chief** and an éditor until he/she has declared the absence of any conflict of interest.

**Comment by rtournoy** [comment]
The settings are in: /review/settings

**Comment by cbarthonnat** [comment]
Créer une page dédiée dans la doc (https://docs.google.com/document/d/1w-zI7V-iKrSzSbwwLWC3HOG5ZQnNC4rjbZMloowWrZM/edit)

**Comment by cbarthonnat** [comment]
Mise à jour de la doc :

- FR : https://doc.episciences.org/fr/settings/#conflit-dinteret
- EN : https://doc.episciences.org/settings/#additional-settings
