### ISSUE TITLE
Managing editors' comments 

### ISSUE THREAD

**Issue by laurentromary** [CCSDForge/episciences#56]
I've just come across an issue in the editors' comments box: when entering a comment and saving it, the text also remains in the comment box leaving the impression that the comment did not go through and when doing things a little bit in haste (like I always do), I clicked a second time and now have a duplicated comment (jdmdh:7277). 
Long story short: the box should be emptied once the comment has been saved.

**Comment by devletech** [comment]
Thank you! The bug has been fixed, the correction appears in the next production release.
