### ISSUE TITLE
[Bug Report] [JTCAM] [SWHID] Faulty error message?

### ISSUE THREAD

**Issue by mlegr** [CCSDForge/episciences#566]
At JTCAM, we have recently noticed that the "Software" box indicates an error message for a supposedly invalid SWHID (see for instance [1]). However, the link seems to be correct and clicking on it redirects to the right webpage.  

[1]  https://jtcam.episciences.org/12218

**Comment by rtournoy** [comment]
thanks for the report, I'm closing this as completed it looks like it has been fixed on Software Heritage's side. Please re-open as needed
