### ISSUE TITLE
[Bug Report] paper remains in the ‘pending minor revision’ phase/status.

### ISSUE THREAD

**Issue by vacary** [CCSDForge/episciences#569]
Dear developpers,

We are currently experiencing a bug on the episciences platform.

After accepting an article, the article enters automatically in  the ‘pending minor revision’ phase. The only options after this are ‘ask for other editor opinion’ or ‘reject the article’. We ask the editor to choose for ‘ask for other editor opinion’.

The problem is that this phase does not end and the paper remains in the ‘pending minor revision’ phase.

For the moment, I’m unblocking the situation by forcing the passage and accepting the paper connecting me as an author. 

Is it possible to know what happens and of we are doing things well

Best

**Comment by devletech** [comment]
On which article did you encounter the problem?

**Comment by vacary** [comment]
On several articles. This one for instance :
https://jtcam.episciences.org/administratepaper/view?id=11269

**Comment by devletech** [comment]
The revision request was made manually by the editor of this article.
> If the revision request is no longer necessary, I can restore the previous status.

**Comment by vacary** [comment]
Yes, but after that the paper has been accpted but nothing happened on the platform and we are stuck.

How to restore the previous status ?

**Comment by devletech** [comment]
Ok done. 

**/!\  The journal allows requests for revisions for accepted preprints:** 

> ![Capture d’écran du 2024-09-12 15-49-27](https://github.com/user-attachments/assets/2b04d938-629a-4d1a-bbf5-918b3c853144)

**/!\ The action ‘Accepted - waiting for author's final version’ will automatically set the status of the article to "pending minor revision"**

> ![Capture d’écran du 2024-09-12 15-48-59](https://github.com/user-attachments/assets/e712f80b-4743-454b-b3d5-0ff8f28041a1)

**Comment by rtournoy** [comment]
Hello, quick follow up: what needs to be done, should we fix something? add a feature? thanks
