### ISSUE TITLE
[Bug Report] journal management table is buggy

### ISSUE THREAD

**Issue by vacary** [CCSDForge/episciences#570]
The journal management table is buggy. The entries
- status
- reviewers,
are not displayed.

The columns are also not aligned.

Problem encountered on google Chrome, Safari, opera GX at least

**Comment by HeleneLowinger** [comment]
Dû au choix de la feuille de style (en conflit avec le back-office) : sera résolu prochainement avec le nouvel environnement

**Comment by vacary** [comment]
ok. fine. Note that this makes article management rather difficult for our editors.
