### ISSUE TITLE
[Feature request] [JTCAM] [software] Not possible to add more than one SWHID

### ISSUE THREAD

**Issue by mlegr** [CCSDForge/episciences#591]
In the "software" tab of an accepted article, it does not seem possible to add more than one SWHID identifier, which does not seem to be justified. Seems to be related to issue [418](https://github.com/CCSDForge/episciences/issues/418)

**Comment by rtournoy** [comment]
it will be fixed with the next release v.1.0.46 and can be tested in the preproduction websites

**Comment by rtournoy** [comment]
fixed in production
