### ISSUE TITLE
[Bug Report] [JTCAM] Manual edition of "Software/Publications/Datasets"

### ISSUE THREAD

**Issue by mlegr** [CCSDForge/episciences#601]
Using publication [10.46298/jtcam.10430](https://doi.org/10.46298/jtcam.10430) as an example, would it be possible to have full manual control of the "Software", "Publication", "Datasets" boxes. At the moment, information that has been retrieved automatically cannot be suppressed. 

![JTCAM](https://github.com/user-attachments/assets/9163cb26-7de6-450a-b845-72282c93719a)

**Comment by rtournoy** [comment]
I will be fixed with the next release. The feature can be tested on the preproduction websites, it will allow to edit the relationships, create new ones, and type the relationship, e.g. this Episciences publication "has a review" => open peer review link.

**Comment by rtournoy** [comment]
and I have deleted the one coming from HAL

**Comment by rtournoy** [comment]
fixed in our production system
