### ISSUE TITLE
[Bug Report] Reviewer comment email %%COMMENT%% tag actually has the answer.

### ISSUE THREAD

**Issue by davidjpurser** [CCSDForge/episciences#607]
When an author responds to a reviewer's comment, the system triggers an email to the reviewer and to the editor. In TheoretiCS called: Author's answer to a reviewer's comment (reviewer copy) and Author's answer to a reviewer's comment (editors copy).

These emails have a %%COMMENT%% tag and an %%ANSWER%%, where %%COMMENT%% should be the original comment from the reviewer to the author and %%ANSWER%% should the response from the author to the reviewer. 
**The problem is, for the EDITORS copy both %%COMMENT%% and %%ANSWER%% are the same and show the answer only.**

The reviewers copy appears to work as expected.

**Comment by davidjpurser** [comment]
As a secondary point, the comment attachment should be attached to the email. I'm not sure if this happens for the author copy, but it does not for the editors.

**Comment by devletech** [comment]
Fixed with release [v1.0.45.2](https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#v10452---2024-10-22)
