### ISSUE TITLE
String not localized

### ISSUE THREAD

**Issue by a3nm** [CCSDForge/episciences#62]
Hello,

On the screenshot below from /administratepaper/list:

![Capture](https://user-images.githubusercontent.com/843551/131452066-cacfa376-6602-4514-ab87-1742f0e7d06f.jpg)

The string "Toutes" should probably be localized to "All".

Thanks!

**Comment by rtournoy** [comment]
Hello, 
thanks a lot for reporting that, the fix is online
best,
Raphaël

**Comment by a3nm** [comment]
Looks perfect! many thanks :)
