### ISSUE TITLE
[Bug Report]manage bibliographic reference

### ISSUE THREAD

**Issue by Arolland-math** [CCSDForge/episciences#622]
here is just to let you know that the Manage system to add the Bibliographic References of the articles on our OCNMP website still does not function for me. I guess this problem has not been solved yet.

**Comment by cbarthonnat** [comment]
problème similaire rencontré par JPE (signalé le 30 Oct 2024 : https://support.ccsd.cnrs.fr/Ticket/Display.html?id=225500)

**Comment by Arolland-math** [comment]
bug dans l'application, meme pb sur JPE
peut etre du à la façon dot sont rentrées les refs ?
