### ISSUE TITLE
[Bug Report] Particular userid not found

### ISSUE THREAD

**Issue by t-wissmann** [CCSDForge/episciences#631]
**Describe the bug**
On lmcs.episciences.org the userid `337578` does not show up in the user list:
https://lmcs.episciences.org/user/list even though the account exists: https://lmcs.episciences.org/user/edit?userid=337578

**To Reproduce**
1. Go to https://lmcs.episciences.org/user/list
2. Enter `472689` in the search field
3. Observe that there is one entry in the table (so search for user ids works).
4. Change the search field to `337578`
5. Observe that the table is empty.

**Expected behavior**
If a user id is valid (such as the above mentioned ones), then it should appear in the user list

**Additional context**
I've noticed the issue because the API endpoint `/api/users/337578` reported 404 even though I obtained the user id from episciences via an api call. But I assume that this is only another symptom of above problem, because the user id is also not listed in `/api/users?pagination=false` 
 
**Screenshots**
![image](https://github.com/user-attachments/assets/52fb8997-3969-4ecf-8b36-f0eb219ea617)

**Browser and Operating System (please complete the following information):**
Linux / qutebrowser

**Comment by t-wissmann** [comment]
Here's another userid with the same issue: `102920`

**Comment by rtournoy** [comment]
Thanks for the report

We have discovered that if you remove the last role of a user we did not add the member role back to keep them in the user list, hence they would disappear from the journal user list, until they logged in again.

It is fixed
