### ISSUE TITLE
Reviewer invitations should expire with the start of copy editing

### ISSUE THREAD

**Issue by t-wissmann** [CCSDForge/episciences#77]
If a paper is in the copy editing process, the referees *must not* be able to click on any old 'accept reviewer invitation' links. Unfortunately, the following happened for paper [7466](https://lmcs.episciences.org/administratepaper/view?id=7466).

  * May 11: The editor accepts the paper ("New status: accepted")
  * May 14: I've started the 'Copy editing' process ("New status: Copy ed.: waiting for author's final version")
  * May 21, Reviewer 1 accepts an review invitation ("New status: under review", I assume this happened by clicking on an invitation link from an old mail)
  * August 13: Review 2 also accepts the review invitation and even submits a review again.

This caused that I lost track of the paper (as a layout editor, I'm not looking at papers that are "under review"), and it caused unnecessary reviewing load for reviewer 2.

What I would have expected: From the point on where the paper is accepted and the copy editing process is started, any old review invitation links should have expired and it should not be possible that the reviewer intervenes the copy editing process.

**Comment by rtournoy** [comment]
Thanks for the report @devletech  as introduced a fix with V1.0.17.1 - 2021-09-28 that should prevent that from happening again. It's online

**Comment by t-wissmann** [comment]
Thanks!
