### ISSUE TITLE
Develop an option to handle conflict of interest (COI)

### ISSUE THREAD

**Issue by rtournoy** [CCSDForge/episciences#81]
**Design for a minimum viable product**

As a chief editor/administrator I want a journal option to enable "**A conflict of interest mode**". This mode will impact all editors of the journal and may be enabled/disabled for a journal without technical side effects at any time.

This mode is disabled by default.

This mode will have the following effects:
All non-public information about a submission is not accessible to an editor until he/she has declared the absence of any conflict of interest. Public information is metadata available on an open archive where the submissions are hosted (e.g. authors/title/abstract, ...).

When this mode is enabled, the reviewers column is not available inside the dashboard and as an editor I can only see public information about submissions until I have declared the absence of conflict of interest (COI).

As an editor I want to be able to see all the submissions of the journal.

As an editor I want to be able to declare a (COI) with a submission. I need to be able to see all public metadata of submissions to be able to identify a COI.
When I want to access confidential information about a submission (the admin page), I would like to be requested to confirm my will with a question.

Question might be:
"You're about to access confidential information about this submission. Would you like to continue or declare a conflict of interest?" (3 Buttons/options  '_No: Declare a conflict of Interest_' or '_Yes: Continue and see submission_' or '_Decide later_')

- If I select 'No', a COI will be registered, logged, optionally with my _explanation_ (text input). I will not be able to access confidential information about the publication. If I try to access the publication admin page again, I will be redirected to the public page of the article and a message will be displayed 'You have declared a conflict of interest, access is not possible' Optionally with my _explanation_. 

- If I select 'Yes', my agreement will be registered, logged, I will access the confidential information and won't be asked again for confirmation

- If I select 'Decide later' I will be redirected to the public page of the article.

**Comment by clason** [comment]
Maybe it would be useful to add an option "automatically enable conflict of interest for own submissions"? That's basically the main use case for me (in the role of Chief Editor): to be able to safely submit papers to the journal I manage.

**Comment by vacary** [comment]
That's would be great!
As administrators and associate editors of JTCAM, we have the same issues with self-submissions. Personally, I didn't submit to the journal I promote because of possible COI.

**Comment by rtournoy** [comment]
I'm closing this but created a new issue for remaining feature requests: https://github.com/CCSDForge/episciences/issues/518
