### ISSUE TITLE
[COI] Journal settings: new setting to Enable/disable COI for journal managers

### ISSUE THREAD

**Issue by rtournoy** [CCSDForge/episciences#83]
Add a new journal setting to enable/disable Conflict Of Interest

COI is Disabled by default

**Comment by clason** [comment]
I think it's not a good idea to label a checkbox "Enable/Disable" ;) (What does setting the checkmark do: enable or disable o.O?)

It should be called just "Enable COI"  -- or better, since you're not enabling the conflict of interest itself -- "Enable declaring CoI"?

**Comment by devletech** [comment]
Checkbox checked => COI  enabled
