### ISSUE TITLE
Add twitter support through user profiles

### ISSUE THREAD

**Issue by laurentromary** [CCSDForge/episciences#95]
It would be good to offer the possibility for author to signal their twitter identities so that we can have them automatically included when tweeting publications from the Episciences interface.

**Comment by laurentromary** [comment]
Since I am pushing some new published papers in JDMDH today, I am still annoyed searching twitter accounts manually.

**Comment by CathScott** [comment]
@Laurent, tu avais demandé la possibilité de mentionner les comptes Twitter dans les profils des utilisateurs et membres du comité éditorial. A présent il est donc possible de renseigner son ou ses affiliations, son ORCID, son compte Twitter en plus de la photo déjà présente. Ces informations apparaîtront alors sur la page de présentation de l'équipe du comité éditorial.

**Comment by CathScott** [comment]
@laurentromary -- tu avais demandé la possibilité de mentionner les comptes Twitter dans les profils des utilisateurs et membres du comité éditorial. A présent il est donc possible de renseigner son ou ses affiliations, son ORCID, son compte Twitter en plus de la photo déjà présente. Ces informations apparaîtront alors sur la page de présentation de l'équipe du comité éditorial.

**Comment by laurentromary** [comment]
Super. Ma demande portait aussi sur les auteurs, car j'aimerait qu'on puisse faire un tweet lors de la publication qui inclue cette information. Est-ce le cas maintenant?

**Comment by CathScott** [comment]
Mise à jour : 
--> faire en sorte que les références Twitter soient automatiquement insérées dans les tweets associés à un article. [JDMDH]
***
Update: 
--> have Twitter references automatically inserted into tweets associated with an article. [JDMDH]

**Comment by laurentromary** [comment]
Scenario: sur la page de l'article, click sur twitter, insertion des twitter des auteurs. 
Rem.: les noms d'auteurs n'était pas encore insérés automatiquement => une occasion de le faire?

**Comment by rtournoy** [comment]
@JcharlesCCSD STP :

Pour les articles avec statut publié :

- [ ] Mettre en place les méta en fonction de la spec [openGraph](https://ogp.me/)
- [ ] Vérifier qu'on ait le nécessaire pour [Twitter summary cards](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary)
- [ ] On doit pouvoir faire pareil pour [Mastodon](https://docs.joinmastodon.org/entities/PreviewCard/)

**Comment by cbarthonnat** [comment]
Pages mises à jour le 27/01/2025 : 

- FR : https://doc.episciences.org/fr/account/
- En : https://doc.episciences.org/account/
